In [1]:
import os
import pandas as pd
from collections import Counter
import tqdm.notebook as tqdm

In [49]:
os.chdir('C:\\Users\\jky93\\KYdrive\\바탕 화면\\SKKU\\7학기\\프로젝트 with 건수\\data from bloomberg')

In [3]:
def shift_q(date):
        if date[4:6]=='01' or date[4:6]=='02'or date[4:6]=='03' :
            date = date[:4] + '0331'
        elif date[4:6]=='04' or date[4:6]=='05'or date[4:6]=='06' :
            date = date[:4] + '0630'
        elif date[4:6]=='07' or date[4:6]=='08' or date[4:6]=='09' :
            date = date[:4] + '0930'
        elif date[4:6]=='10' or date[4:6]=='11'or date[4:6]=='12' :
            date = date[:4] + '1231'
        return date

In [53]:
kospi = pd.read_csv('kospi ff5 data.csv', encoding='cp949', header = 1, index_col=0).iloc[1:,:]
kospi

,006840 KS Equity,006840 KS Equity.1,006840 KS Equity.2,006840 KS Equity.3,006840 KS Equity.4,006840 KS Equity.5,006840 KS Equity.6,006840 KS Equity.7,006840 KS Equity.8,035150 KS Equity,...,006650 KS Equity.8,036580 KS Equity,036580 KS Equity.1,036580 KS Equity.2,036580 KS Equity.3,036580 KS Equity.4,036580 KS Equity.5,036580 KS Equity.6,036580 KS Equity.7,036580 KS Equity.8
2009-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-03-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-12-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
kospi.notna().sum().sum()

147405

In [59]:
def preprocessing_bloomberg(data, number_of_series, *args):
    temp = data.index.map(lambda x: x[:4]+x[5:7]+x[8:10])
    kospi.index = list(map(lambda x: shift_q(x), temp))
    preprocess = dict()
    for i in range(number_of_series):
        finance = kospi.iloc[:,i::number_of_series]
        finance.columns = list(map(lambda x: x[:6], finance.columns))
        real = pd.DataFrame()
        for j in list(set(finance.index)):
            temp = finance.loc[[j],:]
            if temp.shape[0]>1:
                temp.reset_index(inplace=True)
                while temp.shape[0]!=1:
                    temp = temp.append(pd.merge(temp.iloc[[0],:],temp.iloc[[1],:], 'outer'))
                    temp = temp.iloc[:,1:].reset_index().iloc[:, 1:]
                    temp = temp.drop([0,1])
                temp.index= [j]
                real = real.append(temp)
            else:
                real = real.append(temp)
        preprocess[str(arg[i])]=real
    return preprocess

In [60]:
preprocessing_bloomberg(kospi, 9, ['total net asset', 'total asset', 'operating income', 'finance cost', 'net interest expense', 'net interest cost', 'interst expenses operating', 'gross profit', 'net income'])

KeyboardInterrupt:

In [ ]:
data = kospi
number_of_series=9
arg=['total net asset', 'total asset', 'operating income', 'finance cost', 'net interest expense', 'net interest cost', 'interst expenses operating', 'gross profit', 'net income']
temp = data.index.map(lambda x: x[:4]+x[5:7]+x[8:10])
kospi.index = list(map(lambda x: shift_q(x), temp))
preprocess = dict()
for i in tqdm.tqdm(range(number_of_series)):
    finance = kospi.iloc[:,i::number_of_series]
    finance.columns = list(map(lambda x: x[:6], finance.columns))
    real = pd.DataFrame()
    for j in tqdm.tqdm(list(set(finance.index))):
        temp = finance.loc[[j],:]
        # .groupby(level=0, axis=1).last() 를 시도하자
        if temp.shape[0]>1:
            temp.reset_index(inplace=True)
            while temp.shape[0]!=1:
                temp = temp.append(pd.merge(temp.iloc[[0],:],temp.iloc[[1],:], 'outer'))
                temp = temp.iloc[:,1:].reset_index().iloc[:, 1:]
                temp = temp.drop([0,1])
            temp.index= [j]
            real = real.append(temp)
        else:
            real = real.append(temp)
    preprocess[str(arg[i])]=real
preprocess

  0%|          | 0/9 [00:00<?, ?it/s]

  0%|          | 0/53 [00:00<?, ?it/s]

  0%|          | 0/53 [00:00<?, ?it/s]

In [55]:
test = kospi.copy()
number_of_series=9
arg=['total net asset', 'total asset', 'operating income', 'finance cost', 'net interest expense', 'net interest cost', 'interst expenses operating', 'gross profit', 'net income']
temp = test.index.map(lambda x: x[:4]+x[5:7]+x[8:10])
test.index = list(map(lambda x: shift_q(x), temp))
preprocess = dict()
for i in range(number_of_series):
    finance = kospi.iloc[:,i::number_of_series]
    finance.columns = list(map(lambda x: x[:6], finance.columns))
    preprocess[str(arg[i])]=finance
    print('{} is '.format(str(arg[i]))+str(preprocess[str(arg[i])].notna().sum().sum()))
preprocess

total net asset is 0
total asset is 27835
operating income is 29814
finance cost is 1720
net interest expense is 24660
net interest cost is 7045
interst expenses operating is 0
gross profit is 26716
net income is 29615

{'total net asset':            006840 035150 033250 010820 035000 003010 051630 037710 084870  \
 2009-12-31    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-03-31    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-06-30    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-09-30    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-12-31    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 ...           ...    ...    ...    ...    ...    ...    ...    ...    ...
 2021-06-30    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-03-31    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2017-06-29    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-03-30    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-12-30    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN

            000180  ... 204210 229640 089470 069460 075180 402340 126560  \
 2009-12-31    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-03-31    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-06-30    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-09-30    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-12-31    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 ...           ...  ...    ...    ...    ...    ...    ...    ...    ...
 2021-06-30    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-03-31    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2017-06-29    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-03-30    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-12-30    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN

            082640 006650 036580
 2009-12-31    NaN    NaN    NaN
 2010-03-31    NaN    NaN    NaN
 2010-06-30    NaN    NaN    NaN
 2010-09-30    NaN    NaN    NaN
 2010-12-31    NaN    NaN    NaN
 ...           ...    ...    ...
 2021-06-30    NaN    NaN    NaN
 2015-03-31    NaN    NaN    NaN
 2017-06-29    NaN    NaN    NaN
 2015-03-30    NaN    NaN    NaN
 2015-12-30    NaN    NaN    NaN

 [111 rows x 816 columns],
 'total asset':            006840 035150 033250 010820    035000 003010       051630  \
 2009-12-31    NaN    NaN    NaN    NaN       NaN    NaN  23868272051
 2010-03-31    NaN    NaN    NaN    NaN  2.55E+11    NaN  24164277453
 2010-06-30    NaN    NaN    NaN    NaN  3.00E+11    NaN  22852763880
 2010-09-30    NaN    NaN    NaN    NaN  2.82E+11    NaN  23997571443
 2010-12-31    NaN    NaN    NaN    NaN  3.18E+11    NaN  24520084290
 ...           ...    ...    ...    ...       ...    ...          ...
 2021-06-30    NaN    NaN    NaN    NaN       NaN    NaN          NaN
 2015-03-31    NaN    NaN    NaN    NaN       NaN    NaN          NaN
 2017-06-29    NaN    NaN    NaN    NaN       NaN    NaN          NaN
 2015-03-30    NaN    NaN    NaN    NaN       NaN    NaN          NaN
 2015-12-30    NaN    NaN    NaN    NaN       NaN    NaN          NaN

               037710    084870 000180  ... 204210 229640 089470 069460 075180  \
 2009-12-31  2.82E+11       NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN
 2010-03-31  2.91E+11       NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN
 2010-06-30  2.99E+11       NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN
 2010-09-30  3.12E+11       NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN
 2010-12-31  3.31E+11  3.41E+11    NaN  ...    NaN    NaN    NaN    NaN    NaN
 ...              ...       ...    ...  ...    ...    ...    ...    ...    ...
 2021-06-30       NaN       NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN
 2015-03-31       NaN       NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN
 2017-06-29       NaN       NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN
 2015-03-30       NaN       NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN
 2015-12-30       NaN       NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN

            402340 126560 082640 006650 036580
 2009-12-31    NaN    NaN    NaN    NaN    NaN
 2010-03-31    NaN    NaN    NaN    NaN    NaN
 2010-06-30    NaN    NaN    NaN    NaN    NaN
 2010-09-30    NaN    NaN    NaN    NaN    NaN
 2010-12-31    NaN    NaN    NaN    NaN    NaN
 ...           ...    ...    ...    ...    ...
 2021-06-30    NaN    NaN    NaN    NaN    NaN
 2015-03-31    NaN    NaN    NaN    NaN    NaN
 2017-06-29    NaN    NaN    NaN    NaN    NaN
 2015-03-30    NaN    NaN    NaN    NaN    NaN
 2015-12-30    NaN    NaN    NaN    NaN    NaN

 [111 rows x 816 columns],
 'operating income':            006840 035150 033250 010820      035000 003010      051630  \
 2009-12-31    NaN    NaN    NaN    NaN         NaN    NaN   507655530
 2010-03-31    NaN    NaN    NaN    NaN    50373291    NaN  -452562660
 2010-06-30    NaN    NaN    NaN    NaN  5869388133    NaN   327037511
 2010-09-30    NaN    NaN    NaN    NaN  -282337440    NaN   133168910
 2010-12-31    NaN    NaN    NaN    NaN  5773141190    NaN     6158192
 ...           ...    ...    ...    ...         ...    ...         ...
 2021-06-30    NaN    NaN    NaN    NaN         NaN    NaN         NaN
 2015-03-31    NaN    NaN    NaN    NaN         NaN    NaN         NaN
 2017-06-29    NaN    NaN    NaN    NaN         NaN    NaN         NaN
 2015-03-30    NaN    NaN    NaN    NaN         NaN    NaN         NaN
 2015-12-30    NaN    NaN    NaN    NaN         NaN    NaN         NaN

                  037710       084870 000180  ... 204210 229640 089470 069460  \
 2009-12-31  13965896080          NaN    NaN  ...    NaN    NaN    NaN    NaN
 2010-03-31  12427783102   8923235694    NaN  ...    NaN    NaN    NaN    NaN
 2010-06-30  13024680710  11420709296    NaN  ...    NaN    NaN    NaN    NaN
 2010-09-30  10722983160  -2445509158    NaN  ...    NaN    NaN    NaN    NaN
 2010-12-31  16543815450   9364517557    NaN  ...    NaN    NaN    NaN    NaN
 ...                 ...          ...    ...  ...    ...    ...    ...    ...
 2021-06-30          NaN          NaN    NaN  ...    NaN    NaN    NaN    NaN
 2015-03-31          NaN          NaN    NaN  ...    NaN    NaN    NaN    NaN
 2017-06-29          NaN          NaN    NaN  ...    NaN    NaN    NaN    NaN
 2015-03-30          NaN          NaN    NaN  ...    NaN    NaN    NaN    NaN
 2015-12-30          NaN          NaN    NaN  ...    NaN    NaN    NaN    NaN

            075180 402340 126560       082640 006650 036580
 2009-12-31    NaN    NaN    NaN          NaN    NaN    NaN
 2010-03-31    NaN    NaN    NaN          NaN    NaN    NaN
 2010-06-30    NaN    NaN    NaN  43470033391    NaN    NaN
 2010-09-30    NaN    NaN    NaN  67651033841    NaN    NaN
 2010-12-31    NaN    NaN    NaN  77765374257    NaN    NaN
 ...           ...    ...    ...          ...    ...    ...
 2021-06-30    NaN    NaN    NaN          NaN    NaN    NaN
 2015-03-31    NaN    NaN    NaN          NaN    NaN    NaN
 2017-06-29    NaN    NaN    NaN          NaN    NaN    NaN
 2015-03-30    NaN    NaN    NaN          NaN    NaN    NaN
 2015-12-30    NaN    NaN    NaN          NaN    NaN    NaN

 [111 rows x 816 columns],
 'finance cost':            006840 035150 033250 010820 035000 003010 051630 037710 084870  \
 2009-12-31    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-03-31    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-06-30    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-09-30    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-12-31    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 ...           ...    ...    ...    ...    ...    ...    ...    ...    ...
 2021-06-30    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-03-31    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2017-06-29    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-03-30    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-12-30    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN

            000180  ... 204210 229640 089470 069460 075180 402340 126560  \
 2009-12-31    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-03-31    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-06-30    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-09-30    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-12-31    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 ...           ...  ...    ...    ...    ...    ...    ...    ...    ...
 2021-06-30    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-03-31    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2017-06-29    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-03-30    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-12-30    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN

            082640 006650 036580
 2009-12-31    NaN    NaN    NaN
 2010-03-31    NaN    NaN    NaN
 2010-06-30    NaN    NaN    NaN
 2010-09-30    NaN    NaN    NaN
 2010-12-31    NaN    NaN    NaN
 ...           ...    ...    ...
 2021-06-30    NaN    NaN    NaN
 2015-03-31    NaN    NaN    NaN
 2017-06-29    NaN    NaN    NaN
 2015-03-30    NaN    NaN    NaN
 2015-12-30    NaN    NaN    NaN

 [111 rows x 816 columns],
 'net interest expense':            006840 035150 033250 010820 035000 003010     051630 037710  \
 2009-12-31    NaN    NaN    NaN    NaN    NaN    NaN        NaN    NaN
 2010-03-31    NaN    NaN    NaN    NaN    NaN    NaN  -24249440    NaN
 2010-06-30    NaN    NaN    NaN    NaN    NaN    NaN  -19944550    NaN
 2010-09-30    NaN    NaN    NaN    NaN    NaN    NaN        NaN    NaN
 2010-12-31    NaN    NaN    NaN    NaN    NaN    NaN        NaN    NaN
 ...           ...    ...    ...    ...    ...    ...        ...    ...
 2021-06-30    NaN    NaN    NaN    NaN    NaN    NaN        NaN    NaN
 2015-03-31    NaN    NaN    NaN    NaN    NaN    NaN        NaN    NaN
 2017-06-29    NaN    NaN    NaN    NaN    NaN    NaN        NaN    NaN
 2015-03-30    NaN    NaN    NaN    NaN    NaN    NaN        NaN    NaN
 2015-12-30    NaN    NaN    NaN    NaN    NaN    NaN        NaN    NaN

                 084870 000180  ... 204210 229640 089470 069460 075180 402340  \
 2009-12-31         NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN
 2010-03-31  1361902000    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN
 2010-06-30  1335708000    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN
 2010-09-30  1191325000    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN
 2010-12-31  1371745000    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN
 ...                ...    ...  ...    ...    ...    ...    ...    ...    ...
 2021-06-30         NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN
 2015-03-31         NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN
 2017-06-29         NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN
 2015-03-30         NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN
 2015-12-30         NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN

            126560 082640 006650 036580
 2009-12-31    NaN    NaN    NaN    NaN
 2010-03-31    NaN    NaN    NaN    NaN
 2010-06-30    NaN    NaN    NaN    NaN
 2010-09-30    NaN    NaN    NaN    NaN
 2010-12-31    NaN    NaN    NaN    NaN
 ...           ...    ...    ...    ...
 2021-06-30    NaN    NaN    NaN    NaN
 2015-03-31    NaN    NaN    NaN    NaN
 2017-06-29    NaN    NaN    NaN    NaN
 2015-03-30    NaN    NaN    NaN    NaN
 2015-12-30    NaN    NaN    NaN    NaN

 [111 rows x 816 columns],
 'net interest cost':            006840 035150 033250 010820 035000 003010 051630 037710 084870  \
 2009-12-31    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-03-31    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-06-30    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-09-30    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-12-31    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 ...           ...    ...    ...    ...    ...    ...    ...    ...    ...
 2021-06-30    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-03-31    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2017-06-29    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-03-30    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-12-30    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN

            000180  ... 204210 229640 089470 069460 075180 402340 126560  \
 2009-12-31    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-03-31    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-06-30    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-09-30    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-12-31    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 ...           ...  ...    ...    ...    ...    ...    ...    ...    ...
 2021-06-30    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-03-31    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2017-06-29    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-03-30    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-12-30    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN

            082640 006650 036580
 2009-12-31    NaN    NaN    NaN
 2010-03-31    NaN    NaN    NaN
 2010-06-30    NaN    NaN    NaN
 2010-09-30    NaN    NaN    NaN
 2010-12-31    NaN    NaN    NaN
 ...           ...    ...    ...
 2021-06-30    NaN    NaN    NaN
 2015-03-31    NaN    NaN    NaN
 2017-06-29    NaN    NaN    NaN
 2015-03-30    NaN    NaN    NaN
 2015-12-30    NaN    NaN    NaN

 [111 rows x 816 columns],
 'interst expenses operating':            006840 035150 033250 010820 035000 003010 051630 037710 084870  \
 2009-12-31    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-03-31    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-06-30    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-09-30    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-12-31    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 ...           ...    ...    ...    ...    ...    ...    ...    ...    ...
 2021-06-30    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-03-31    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2017-06-29    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-03-30    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-12-30    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN

            000180  ... 204210 229640 089470 069460 075180 402340 126560  \
 2009-12-31    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-03-31    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-06-30    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-09-30    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2010-12-31    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 ...           ...  ...    ...    ...    ...    ...    ...    ...    ...
 2021-06-30    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-03-31    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2017-06-29    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-03-30    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
 2015-12-30    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN

            082640 006650 036580
 2009-12-31    NaN    NaN    NaN
 2010-03-31    NaN    NaN    NaN
 2010-06-30    NaN    NaN    NaN
 2010-09-30    NaN    NaN    NaN
 2010-12-31    NaN    NaN    NaN
 ...           ...    ...    ...
 2021-06-30    NaN    NaN    NaN
 2015-03-31    NaN    NaN    NaN
 2017-06-29    NaN    NaN    NaN
 2015-03-30    NaN    NaN    NaN
 2015-12-30    NaN    NaN    NaN

 [111 rows x 816 columns],
 'gross profit':            006840 035150 033250 010820       035000 003010      051630  \
 2009-12-31    NaN    NaN    NaN    NaN          NaN    NaN  1920924931
 2010-03-31    NaN    NaN    NaN    NaN  14004693432    NaN  1036654720
 2010-06-30    NaN    NaN    NaN    NaN  21745061134    NaN  1783930808
 2010-09-30    NaN    NaN    NaN    NaN  16627024400    NaN  1637057533
 2010-12-31    NaN    NaN    NaN    NaN  28579274428    NaN  1388793860
 ...           ...    ...    ...    ...          ...    ...         ...
 2021-06-30    NaN    NaN    NaN    NaN          NaN    NaN         NaN
 2015-03-31    NaN    NaN    NaN    NaN          NaN    NaN         NaN
 2017-06-29    NaN    NaN    NaN    NaN          NaN    NaN         NaN
 2015-03-30    NaN    NaN    NaN    NaN          NaN    NaN         NaN
 2015-12-30    NaN    NaN    NaN    NaN          NaN    NaN         NaN

                  037710       084870 000180  ... 204210 229640 089470 069460  \
 2009-12-31  34106392820          NaN    NaN  ...    NaN    NaN    NaN    NaN
 2010-03-31  32419241720  51427093694    NaN  ...    NaN    NaN    NaN    NaN
 2010-06-30  33205435280  52477185296    NaN  ...    NaN    NaN    NaN    NaN
 2010-09-30  30771761762  42755147842    NaN  ...    NaN    NaN    NaN    NaN
 2010-12-31  38807785360  80735469557    NaN  ...    NaN    NaN    NaN    NaN
 ...                 ...          ...    ...  ...    ...    ...    ...    ...
 2021-06-30          NaN          NaN    NaN  ...    NaN    NaN    NaN    NaN
 2015-03-31          NaN          NaN    NaN  ...    NaN    NaN    NaN    NaN
 2017-06-29          NaN          NaN    NaN  ...    NaN    NaN    NaN    NaN
 2015-03-30          NaN          NaN    NaN  ...    NaN    NaN    NaN    NaN
 2015-12-30          NaN          NaN    NaN  ...    NaN    NaN    NaN    NaN

            075180 402340 126560 082640 006650 036580
 2009-12-31    NaN    NaN    NaN    NaN    NaN    NaN
 2010-03-31    NaN    NaN    NaN    NaN    NaN    NaN
 2010-06-30    NaN    NaN    NaN    NaN    NaN    NaN
 2010-09-30    NaN    NaN    NaN    NaN    NaN    NaN
 2010-12-31    NaN    NaN    NaN    NaN    NaN    NaN
 ...           ...    ...    ...    ...    ...    ...
 2021-06-30    NaN    NaN    NaN    NaN    NaN    NaN
 2015-03-31    NaN    NaN    NaN    NaN    NaN    NaN
 2017-06-29    NaN    NaN    NaN    NaN    NaN    NaN
 2015-03-30    NaN    NaN    NaN    NaN    NaN    NaN
 2015-12-30    NaN    NaN    NaN    NaN    NaN    NaN

 [111 rows x 816 columns],
 'net income':            006840 035150 033250 010820      035000 003010      051630  \
 2009-12-31    NaN    NaN    NaN    NaN         NaN    NaN   572911053
 2010-03-31    NaN    NaN    NaN    NaN     2366380    NaN  -213672570
 2010-06-30    NaN    NaN    NaN    NaN  4764792553    NaN   343693802
 2010-09-30    NaN    NaN    NaN    NaN   553604060    NaN   336413950
 2010-12-31    NaN    NaN    NaN    NaN  6290930680    NaN   120582450
 ...           ...    ...    ...    ...         ...    ...         ...
 2021-06-30    NaN    NaN    NaN    NaN         NaN    NaN         NaN
 2015-03-31    NaN    NaN    NaN    NaN         NaN    NaN         NaN
 2017-06-29    NaN    NaN    NaN    NaN         NaN    NaN         NaN
 2015-03-30    NaN    NaN    NaN    NaN         NaN    NaN         NaN
 2015-12-30    NaN    NaN    NaN    NaN         NaN    NaN         NaN

                  037710       084870 000180  ... 204210 229640 089470 069460  \
 2009-12-31  11567081700          NaN    NaN  ...    NaN    NaN    NaN    NaN
 2010-03-31  10578741943   2939575694    NaN  ...    NaN    NaN    NaN    NaN
 2010-06-30  11050244030   5631792634    NaN  ...    NaN    NaN    NaN    NaN
 2010-09-30   9344155070  -2555030855    NaN  ...    NaN    NaN    NaN    NaN

In [69]:
preprocess['total asset'].T.groupby(level=0, axis=1).last()

,2009-12-30,2009-12-31,2010-03-31,2010-06-30,2010-09-30,2010-12-31,2011-03-31,2011-06-30,2011-09-30,2011-12-31,...,2021-05-31,2021-06-30,2021-08-31,2021-09-30,2021-11-30,2021-12-31,2022-09-30,2023-09-30,2024-09-30,2025-09-30
006840,None,None,None,None,None,None,None,None,None,None,...,None,4.31E+12,None,4.36E+12,None,None,None,None,None,None
035150,None,None,None,None,None,None,None,None,None,None,...,None,3.07E+11,None,3.03E+11,None,None,None,None,None,None
033250,None,None,None,None,None,None,None,None,None,None,...,None,81159742752,None,77774699420,None,None,None,None,None,None
010820,None,None,None,None,None,None,None,None,None,None,...,None,2.02E+11,None,1.98E+11,None,None,None,None,None,None
035000,None,None,2.55E+11,3.00E+11,2.82E+11,3.18E+11,2.92E+11,3.41E+11,3.27E+11,3.67E+11,...,None,4.34E+11,None,4.72E+11,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402340,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
126560,None,None,None,None,None,None,5.79E+11,5.83E+11,5.91E+11,5.96E+11,...,None,1.01E+12,None,1.07E+12,None,None,None,None,None,None
082640,None,None,None,None,None,None,1.29E+13,1.32E+13,1.35E+13,1.40E+13,...,None,3.63E+13,None,3.65E+13,None,None,None,None,None,None
006650,None,None,None,None,None,None,None,None,None,None,...,None,2.41E+12,None,2.43E+12,None,None,None,None,None,None
036580,None,None,None,None,None,None,None,None,None,None,...,None,1.06E+12,None,1.12E+12,None,None,None,None,None,None

In [58]:
data = preprocess['total asset']
real = pd.DataFrame()
for j in tqdm.tqdm(list(set(data.index))):
    temp = data.loc[[j],:]
    if temp.shape[0]>1:
        temp.reset_index(inplace=True)
        while temp.shape[0]!=1:
            temp = temp.append(pd.merge(temp.iloc[[0],:],temp.iloc[[1],:], 'outer'))
            temp = temp.iloc[:,1:].reset_index().iloc[:, 1:]
            temp = temp.drop([0,1])
        temp.index= [j]
        real = real.append(temp)
    else:
        real = real.append(temp)

  0%|          | 0/98 [00:00<?, ?it/s]

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [31]:
real.sort_index().isna().sum().sum()

43248