In [1]:
pip install fmp_python

Collecting fmp_python
  Downloading fmp_python-0.1.4-py3-none-any.whl (9.0 kB)
Requirement already satisfied: requests in c:\users\jky93\anaconda3\lib\site-packages (from fmp_python) (2.27.1)
Requirement already satisfied: pandas in c:\users\jky93\anaconda3\lib\site-packages (from fmp_python) (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\jky93\anaconda3\lib\site-packages (from pandas->fmp_python) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in c:\users\jky93\anaconda3\lib\site-packages (from pandas->fmp_python) (1.21.5)
Requirement already satisfied: pytz>=2017.3 in c:\users\jky93\anaconda3\lib\site-packages (from pandas->fmp_python) (2021.3)
Requirement already satisfied: six>=1.5 in c:\users\jky93\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas->fmp_python) (1.16.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\jky93\anaconda3\lib\site-packages (from requests->fmp_python) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\jky93\anaconda3\lib\site-packages (from requests->fmp_python) (1.26.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jky93\anaconda3\lib\site-packages (from requests->fmp_python) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jky93\anaconda3\lib\site-packages (from requests->fmp_python) (3.3)
Installing collected packages: fmp-python
Successfully installed fmp-python-0.1.4
Note: you may need to restart the kernel to use updated packages.

In [44]:
from fmp_python.fmp import FMP
api_key = '8ede72aa30eb534c51f15eaa71ff2e05'

fmp = FMP(api_key=api_key, output_format='pandas', write_to_file=True)
fmp.get_quote('MPAY')

Empty DataFrame
Columns: []
Index: []

In [45]:
fmp.get_quote_short('MVP')

  symbol   price  volume
0    MVP  12.325    1027

In [48]:
fmp.get_historical_chart('1min','TSLA')

                    date      open     low      high     close  volume
0    2022-06-23 09:38:00  696.2300  695.99  698.6999  696.0000  192155
1    2022-06-23 09:37:00  702.3500  695.55  702.4910  695.9900  379352
2    2022-06-23 09:36:00  701.9396  701.27  704.3500  702.3301  189154
3    2022-06-23 09:35:00  708.0550  701.17  708.4599  701.9300  319385
4    2022-06-23 09:34:00  709.7630  707.92  711.8828  708.2600  158089
..                   ...       ...     ...       ...       ...     ...
663  2022-06-21 11:37:00  719.8200  718.58  720.2753  718.7358  114368
664  2022-06-21 11:36:00  721.2801  719.37  721.4950  719.8446   84974
665  2022-06-21 11:35:00  720.5610  719.65  722.0050  721.5333  143281
666  2022-06-21 11:34:00  722.4500  720.55  722.4500  720.8585  124092
667  2022-06-21 11:33:00  722.2900  721.88  722.7400  722.3400   77260

[668 rows x 6 columns]

In [9]:
try:
    # For Python 3.0 and later
    from urllib.request import urlopen
except ImportError:
    # Fall back to Python 2's urllib2
    from urllib2 import urlopen

import certifi
import json

def get_jsonparsed_data(url):
    """
    Receive the content of ``url``, parse it as JSON and return the object.

    Parameters
    ----------
    url : str

    Returns
    -------
    dict
    """
    response = urlopen(url, cafile=certifi.where())
    data = response.read().decode("utf-8")
    return json.loads(data)

url = ("https://financialmodelingprep.com/api/v3/financial-statement-symbol-lists?apikey=8ede72aa30eb534c51f15eaa71ff2e05")
print(len(get_jsonparsed_data(url)))

C:\Users\jky93\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: DeprecationWarning: cafile, capath and cadefault are deprecated, use a custom context instead.

38212

In [20]:
import pandas as pd
url = "https://financialmodelingprep.com/api/v3/balance-sheet-statement/AAPL?apikey=8ede72aa30eb534c51f15eaa71ff2e05&limit=300"
pd.DataFrame(get_jsonparsed_data(url))

C:\Users\jky93\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: DeprecationWarning: cafile, capath and cadefault are deprecated, use a custom context instead.

,date,symbol,reportedCurrency,cik,fillingDate,acceptedDate,calendarYear,period,cashAndCashEquivalents,shortTermInvestments,...,totalStockholdersEquity,totalLiabilitiesAndStockholdersEquity,minorityInterest,totalEquity,totalLiabilitiesAndTotalEquity,totalInvestments,totalDebt,netDebt,link,finalLink
0,2021-09-25,AAPL,USD,0000320193,2021-10-29,2021-10-28 18:04:28,2021,FY,34940000000,27699000000,...,63090000000,351002000000,0,63090000000,351002000000,155576000000,124719000000,89779000000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
1,2020-09-26,AAPL,USD,0000320193,2020-10-30,2020-10-29 18:06:25,2020,FY,38016000000,52927000000,...,65339000000,323888000000,0,65339000000,323888000000,153814000000,112436000000,74420000000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
2,2019-09-28,AAPL,USD,0000320193,2019-10-31,2019-10-30 18:12:36,2019,FY,48844000000,51713000000,...,90488000000,338516000000,0,90488000000,338516000000,157054000000,108047000000,59203000000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
3,2018-09-29,AAPL,USD,0000320193,2018-11-05,2018-11-05 08:01:40,2018,FY,25913000000,40388000000,...,107147000000,365725000000,0,107147000000,365725000000,211187000000,114483000000,88570000000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...
4,2017-09-30,AAPL,USD,0000320193,2017-11-03,2017-11-03 08:01:37,2017,FY,20289000000,53892000000,...,134047000000,375319000000,0,134047000000,375319000000,248606000000,115680000000,95391000000,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...

In [39]:
url = 'https://financialmodelingprep.com/api/v3/cash-flow-statement/TSLA?apikey=8ede72aa30eb534c51f15eaa71ff2e05&limit=500'
pd.DataFrame(get_jsonparsed_data(url))

C:\Users\jky93\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: DeprecationWarning: cafile, capath and cadefault are deprecated, use a custom context instead.

,date,symbol,reportedCurrency,cik,fillingDate,acceptedDate,calendarYear,period,netIncome,depreciationAndAmortization,...,netCashUsedProvidedByFinancingActivities,effectOfForexChangesOnCash,netChangeInCash,cashAtEndOfPeriod,cashAtBeginningOfPeriod,operatingCashFlow,capitalExpenditure,freeCashFlow,link,finalLink
0,2021-12-31,TSLA,USD,0001318605,2022-02-07,2022-02-04 20:11:27,2021,FY,5519000000,2911000000,...,-5203000000,-183000000.0,-1757000000,18144000000,19901000000,11497000000,-8014000000,3483000000,https://www.sec.gov/Archives/edgar/data/131860...,https://www.sec.gov/Archives/edgar/data/131860...
1,2020-12-31,TSLA,USD,0001318605,2021-02-08,2021-02-08 07:27:23,2020,FY,690000000,2322000000,...,9973000000,334000000.0,13118000000,19901000000,6783000000,5943000000,-3242000000,2701000000,https://www.sec.gov/Archives/edgar/data/131860...,https://www.sec.gov/Archives/edgar/data/131860...
2,2019-12-31,TSLA,USD,0001318605,2020-02-13,2020-02-13 07:12:18,2019,FY,-862000000,2154000000,...,1529000000,8000000.0,2506000000,6783000000,4277000000,2405000000,-1437000000,968000000,https://www.sec.gov/Archives/edgar/data/131860...,https://www.sec.gov/Archives/edgar/data/131860...
3,2018-12-31,TSLA,USD,0001318605,2019-02-19,2019-02-19 06:10:16,2018,FY,-976091000,1901050000,...,573755000,-22700000.0,311429000,4276388000,3964959000,2097802000,-2319516000,-221714000,https://www.sec.gov/Archives/edgar/data/131860...,https://www.sec.gov/Archives/edgar/data/131860...
4,2017-12-31,TSLA,USD,0001318605,2018-02-23,2018-02-23 06:07:43,2017,FY,-1961400000,1636003000,...,4414864000,39455000.0,-25302000,3367914000,3393216000,-60654000,-4081354000,-4142008000,https://www.sec.gov/Archives/edgar/data/131860...,https://www.sec.gov/Archives/edgar/data/131860...

In [30]:
result = []
for i in range(10):
    url = "https://financialmodelingprep.com/api/v3/delisted-companies?page="+str(i)+"&apikey=8ede72aa30eb534c51f15eaa71ff2e05"
    result.append(get_jsonparsed_data(url))
pd.DataFrame(result[0])

C:\Users\jky93\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: DeprecationWarning: cafile, capath and cadefault are deprecated, use a custom context instead.

,symbol,companyName,exchange,ipoDate,delistedDate
0,MVP,Roundhill Pro Sports Media & Apparel ETF,NYSE ARCA,2021-03-17,2022-06-21
1,JPNL,DIREXION DAILY MSCI JAPAN BULL 3X SHARES,NYSE ARCA,2013-06-26,2022-06-21
2,KNL,Knoll Inc,NYSE,2004-12-14,2022-06-21
3,IRCP,Irsa Propiedades Comerciales S.A.,NASDAQ,2003-11-05,2022-06-21
4,CYPS,Cyclo3pss Corp,NASDAQ,2007-07-16,2022-06-21
...,...,...,...,...,...
95,TUGCU,SAI.TECH Global Corporation - Units (1 Ord Sha...,NASDAQ,2021-04-29,2022-04-29
96,WTRU,Essential Utilities Inc,NYSE,2019-04-18,2022-04-29
97,BIGY,Defiance Next Gen Big Data ETF,NYSE ARCA,2021-07-14,2022-04-28
98,GWGHQ,GWG Holdings Inc,NASDAQ,2014-09-25,2022-04-28
99,ATSPU,SoundHound AI Inc - Units (1 Subunit & 1/4 War),NASDAQ,2021-03-11,2022-04-27

In [35]:
pd.DataFrame(result[1])

,symbol,companyName,exchange,ipoDate,delistedDate
0,ATSPT,SoundHound AI Inc - Subunit (1 Ord & 1/4 War),NASDAQ,2021-04-23,2022-04-27
1,BUDX,Cannabis Growth ETF,NYSE ARCA,2021-09-27,2022-04-25
2,VOLT,Volt Information Sciences Inc,NYSE MKT,1990-03-26,2022-04-25
3,CHPMW,CHP Merger Corp - Warrants (22/11/2024),NASDAQ,2020-01-10,2022-04-22
4,CHPMU,CHP Merger Corp - Units (1 Ord Class A & 1/2 War),NASDAQ,2019-11-22,2022-04-22
...,...,...,...,...,...
95,ECCY,Eagle Point Credit Company Inc,NYSE,2017-08-09,2022-02-11
96,NXU-U,Energy Vault Holdings Inc - Units (1 Ord Share...,NYSE,2021-02-04,2022-02-11
97,GCACU,Cepton Inc - Units (1 Ord Share Class A & 1/2 ...,NASDAQ,2021-01-29,2022-02-10
98,SBEAU,BRC Inc - Units (1 Ord Share Class A & 1/3 War),NASDAQ,2021-02-26,2022-02-09
99,CCAC,Quanergy Systems Inc - Class A,NYSE,2020-04-23,2022-02-09

In [2]:
import pandas as pd

In [15]:
code = 'AAPL'
api_key = '8ede72aa30eb534c51f15eaa71ff2e05'
url = "https://financialmodelingprep.com/api/v3/financial-growth/{}?apikey={}".format(code, api_key)
pd_g = pd.read_json(url)
growth_rate = np.mean(pd_g['dividendsperShareGrowth'].iloc[:10])

In [16]:
growth_rate

0     0.067451
1     0.061635
2     0.104947
3     0.130598
4     0.102027
5     0.105235
6     0.099086
7     0.120997
8     3.289513
9     0.000000
10    0.000000
11    0.000000
12    0.000000
13    0.000000
14    0.000000
15    0.000000
16    0.000000
17    0.000000
18    0.000000
19    0.000000
20    0.000000
21    0.000000
22    0.000000
23    0.000000
24   -1.000000
25   -0.759961
26   -0.010686
27    0.002846
28    0.015094
29   -0.005292
30    0.098790
31    0.091834
32    0.000000
33    0.000000
34    0.000000
35    0.000000
36    0.000000
Name: dividendsperShareGrowth, dtype: float64