In [1]:
import numpy as np
import pandas as pd
import os
from scipy.stats.mstats import winsorize
import sys

In [2]:
mktcap = pd.read_csv('MarketCap.csv', index_col=0, encoding = 'utf8')
bv = pd.read_csv('AT.csv', index_col=0,  encoding = 'utf8')

In [3]:
bv = pd.DataFrame(bv)
bv.index = pd.to_datetime(bv.index)
bv

,001003,001004,001009,001011,001012,001013,001015,001016,001017,001019,...,315887,316056,317260,317264,317427,318728,326688,327451,328032,328795
date,,,,,,,,,,,,,,,,,,,,,
1987-01-31,14.586,NaN,NaN,6.502,NaN,NaN,NaN,NaN,NaN,16.667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-02-28,14.586,NaN,NaN,6.502,NaN,NaN,NaN,NaN,90.447,16.667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-03-31,14.586,NaN,NaN,6.502,NaN,NaN,NaN,NaN,90.447,16.667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-04-30,14.586,NaN,NaN,6.502,NaN,NaN,NaN,NaN,90.447,16.667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-05-31,14.586,235.091,NaN,6.502,NaN,NaN,NaN,NaN,90.447,16.667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-07-31,NaN,1524.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1643.41,2542.0,387.711,1736.11,5532.164,99747.0,4725.0,507.122,266.811,1602.5
2018-08-31,NaN,1524.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1643.41,2542.0,387.711,1736.11,5532.164,99747.0,4725.0,507.122,266.811,1602.5
2018-09-30,NaN,1524.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1643.41,2542.0,387.711,1736.11,5532.164,99747.0,4725.0,507.122,266.811,1602.5
2018-10-31,NaN,1524.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1643.41,2542.0,387.711,1736.11,5532.164,99747.0,4725.0,507.122,266.811,1602.5
2018-11-30,NaN,1524.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1643.41,2542.0,387.711,1736.11,5532.164,99747.0,4725.0,507.122,266.811,1602.5

In [4]:
precol = mktcap.columns
mktcap.columns = [i[:-3] for i in precol]

In [5]:
mktcap = pd.DataFrame(mktcap)
mktcap.index =pd.to_datetime(mktcap.index)
mktcap

,001690,012141,160329,064768,184996,170617,117768,002176,010903,002968,...,329579,330826,331125,335466,339950,343180,345189,345556,347085,349972
date,,,,,,,,,,,,,,,,,,,,,
1986-12-31,2.541416e+03,1.254210e+03,NaN,NaN,NaN,NaN,NaN,3234.540000,128.832625,2114.908250,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-01-31,3.482681e+03,1.900809e+03,NaN,NaN,NaN,NaN,NaN,3555.700000,107.681000,2346.421875,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-02-28,4.392570e+03,1.995038e+03,NaN,NaN,NaN,NaN,NaN,3853.920000,117.295375,2327.650500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-03-31,4.129161e+03,2.529622e+03,NaN,NaN,NaN,NaN,NaN,4037.440000,121.684500,2225.037500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-04-30,5.073427e+03,2.719183e+03,NaN,NaN,NaN,NaN,NaN,3876.860000,77.260000,2161.465000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-31,2.513841e+06,2.269836e+06,1.932108e+06,1756219.74,723948.48,1072127.88,558729.60,647006.462474,392542.610000,477955.392250,...,NaN,NaN,NaN,0.34463,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-30,2.324390e+06,2.117219e+06,1.777041e+06,1665515.28,778581.92,947916.27,517071.36,611288.979240,368077.080000,483747.491540,...,NaN,NaN,NaN,0.34463,NaN,NaN,NaN,NaN,NaN,NaN
2021-10-31,2.460733e+06,2.490466e+06,1.968070e+06,1709822.01,1118456.00,903731.01,639686.34,643271.115258,433762.740000,502070.140740,...,NaN,NaN,NaN,0.34463,NaN,NaN,NaN,NaN,NaN,NaN
2021-11-30,2.715348e+06,2.482731e+06,1.886334e+06,1778084.49,1149339.04,906216.78,817553.52,619457.266181,418455.240000,469384.898780,...,NaN,NaN,NaN,0.34463,NaN,NaN,NaN,NaN,NaN,NaN
2021-12-31,2.916904e+06,2.525763e+06,1.925610e+06,1690510.38,1061007.12,939425.55,735863.22,669661.603190,473015.880000,467966.371100,...,NaN,NaN,NaN,0.34463,NaN,NaN,NaN,NaN,NaN,NaN

### pct_change 값이 inf가 나오는 애들 때문에 0을 0.1로 다 바꿈

In [378]:
mktcap.isin([0]).sum(1)

date
1986-12-31     2
1987-01-31     2
1987-02-28     3
1987-03-31     2
1987-04-30     2
              ..
2021-08-31    24
2021-09-30    24
2021-10-31    24
2021-11-30    24
2021-12-31    24
Length: 421, dtype: int64

In [379]:
mktcap = mktcap.replace(0, 0.1)

In [380]:
mktcap.isin([0]).sum(1)

date
1986-12-31    0
1987-01-31    0
1987-02-28    0
1987-03-31    0
1987-04-30    0
             ..
2021-08-31    0
2021-09-30    0
2021-10-31    0
2021-11-30    0
2021-12-31    0
Length: 421, dtype: int64

### 가가 데이터셋이 gvkey가 중복되는 것 있나 확인

In [6]:
from collections import Counter
Counter(mktcap.columns).most_common(2)

[('001690', 1), ('012141', 1)]

In [7]:
Counter(bv.columns).most_common(2)

[('001003', 1), ('001004', 1)]

### 일단 gvkey를 bv 18512개에 맞춤

In [8]:
for i in mktcap.columns:
    if i not in bv.columns:
        del mktcap[i]
mktcap

,001690,012141,160329,064768,184996,170617,117768,002176,010903,002968,...,294007,296318,296753,296944,297209,298092,311524,314866,317260,328032
date,,,,,,,,,,,,,,,,,,,,,
1986-12-31,2.541416e+03,1.254210e+03,NaN,NaN,NaN,NaN,NaN,3234.540000,128.832625,2114.908250,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-01-31,3.482681e+03,1.900809e+03,NaN,NaN,NaN,NaN,NaN,3555.700000,107.681000,2346.421875,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-02-28,4.392570e+03,1.995038e+03,NaN,NaN,NaN,NaN,NaN,3853.920000,117.295375,2327.650500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-03-31,4.129161e+03,2.529622e+03,NaN,NaN,NaN,NaN,NaN,4037.440000,121.684500,2225.037500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-04-30,5.073427e+03,2.719183e+03,NaN,NaN,NaN,NaN,NaN,3876.860000,77.260000,2161.465000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-31,2.513841e+06,2.269836e+06,1.932108e+06,1756219.74,723948.48,1072127.88,558729.60,647006.462474,392542.610000,477955.392250,...,11.595225,2543.75904,1318.88545,1.80855,2.929157,NaN,1729.936,3391.25354,8.4801,299.47658
2021-09-30,2.324390e+06,2.117219e+06,1.777041e+06,1665515.28,778581.92,947916.27,517071.36,611288.979240,368077.080000,483747.491540,...,11.595225,2543.75904,1318.88545,1.80855,2.929157,NaN,1729.936,3391.25354,8.4801,299.47658
2021-10-31,2.460733e+06,2.490466e+06,1.968070e+06,1709822.01,1118456.00,903731.01,639686.34,643271.115258,433762.740000,502070.140740,...,11.595225,2543.75904,1318.88545,1.80855,2.929157,NaN,1729.936,3391.25354,8.4801,299.47658
2021-11-30,2.715348e+06,2.482731e+06,1.886334e+06,1778084.49,1149339.04,906216.78,817553.52,619457.266181,418455.240000,469384.898780,...,11.595225,2543.75904,1318.88545,1.80855,2.929157,NaN,1729.936,3391.25354,8.4801,299.47658
2021-12-31,2.916904e+06,2.525763e+06,1.925610e+06,1690510.38,1061007.12,939425.55,735863.22,669661.603190,473015.880000,467966.371100,...,11.595225,2543.75904,1318.88545,1.80855,2.929157,NaN,1729.936,3391.25354,8.4801,299.47658

### 분위 정하기 (SMB은 mktcap기준 1:3 // value, growth는 HML은 BE/ME기준 3:4:3)
#### FF논문에 Size의 기준은 NYSE의 median으로 잡았고, 그러면 비율이 1:3정도 됐다고 함)
#### 6월 30일 기준으로 ranking 정해서 분위 정함

In [15]:
mktcap_rank = mktcap.rank(1, 'first').apply(lambda x: pd.qcut(x, q=4, labels = range(1,5)) if not x.isnull().all() else x, 1)
mktcap_6m = mktcap_rank.groupby(mktcap_rank.index.month).get_group(6)

In [16]:
def extract_portfolio(data, n): #여기서 data는 각 date에 해당하는 series, (series의 index는 티커, name은 date)
    extract = pd.DataFrame(data==n)
    return list(extract[extract[data.name]==True].index)

In [17]:
def portfolio_groups(data, r):
    return [extract_portfolio(data, n) for n in r]

In [18]:
mktcap_port = mktcap_6m.apply(lambda x: portfolio_groups(x, range(1,5)), axis=1,result_type = 'expand')
mktcap_port.columns = ['MktCap{}'.format(i) for i in range(1,5)]
mktcap_port

,MktCap1,MktCap2,MktCap3,MktCap4
date,,,,
1987-06-30,"[011811, 008644, 012140, 009063, 010991, 00955...","[013421, 014275, 012441, 013510, 015417, 00556...","[010903, 003735, 001704, 006565, 012635, 01009...","[001690, 012141, 002176, 002968, 006266, 00568..."
1988-06-30,"[014477, 017120, 011811, 008644, 012140, 00906...","[002710, 014275, 001327, 013510, 015417, 00556...","[010903, 013988, 006565, 011856, 012635, 01009...","[001690, 012141, 002176, 002968, 006266, 00568..."
1989-06-30,"[014477, 015414, 011811, 008644, 009063, 01624...","[002710, 017120, 014275, 012850, 001327, 01351...","[010903, 006565, 014489, 012635, 010096, 00630...","[001690, 012141, 002176, 002968, 006266, 00568..."
1990-06-30,"[014477, 011811, 012140, 014561, 009273, 00955...","[014275, 012850, 001327, 013510, 015414, 01541...","[006565, 012635, 010096, 006304, 004016, 00840...","[001690, 012141, 002176, 010903, 002968, 00626..."
1991-06-30,"[014561, 009273, 009551, 003969, 008512, 02154...","[024316, 001327, 013510, 012459, 005567, 02090...","[006565, 014477, 023812, 010096, 024197, 00271...","[001690, 012141, 002176, 010903, 002968, 00626..."
1992-06-30,"[024316, 008644, 014561, 009273, 009551, 00959...","[001327, 013510, 012459, 005567, 020904, 01357...","[025434, 006565, 024856, 014477, 023812, 01009...","[001690, 012141, 002176, 010903, 002968, 00626..."
1993-06-30,"[012459, 003504, 025274, 014561, 009551, 00959...","[024316, 024468, 001327, 013510, 005567, 02090...","[014477, 023812, 010096, 024344, 027965, 02818...","[001690, 012141, 002176, 010903, 002968, 00626..."
1994-06-30,"[025274, 014561, 028806, 006223, 009551, 00959...","[028877, 024316, 024468, 001327, 030098, 00350...","[024856, 014477, 023812, 024344, 028180, 02461...","[001690, 012141, 002176, 010903, 002968, 00626..."
1995-06-30,"[024316, 025274, 028806, 009551, 020791, 00851...","[028877, 030662, 010789, 003504, 005567, 02090...","[023812, 024344, 028180, 024617, 009248, 01712...","[001690, 012141, 002176, 010903, 002968, 00626..."
1996-06-30,"[024316, 012181, 028806, 030612, 020791, 02563...","[028877, 024617, 061420, 010789, 013570, 06165...","[017120, 025340, 031887, 005543, 014275, 02606...","[001690, 012141, 002176, 010903, 002968, 00626..."
1997-06-30,"[024316, 012181, 028806, 009551, 014027, 03061...","[028877, 029453, 001327, 061420, 010789, 06296...","[023812, 024617, 025340, 031887, 014275, 02990...","[001690, 012141, 064768, 002176, 010903, 00296..."
1998-06-30,"[028877, 028806, 009551, 014027, 030612, 02840...","[024316, 029453, 064630, 061685, 012181, 01357...","[023812, 111864, 110732, 024617, 031887, 01427...","[001690, 012141, 064768, 002176, 010903, 00296..."
1999-06-30,"[028806, 009551, 014027, 030612, 028408, 06171...","[028877, 024316, 029453, 020904, 061685, 01218...","[023812, 111864, 121382, 024617, 014275, 06308...","[001690, 012141, 064768, 117768, 002176, 01090..."
2000-06-30,"[062689, 030651, 028806, 030612, 125794, 02951...","[028877, 024316, 024617, 029453, 064410, 06296...","[136725, 110732, 005543, 014275, 063080, 01137...","[001690, 012141, 064768, 117768, 002176, 01090..."
2001-06-30,"[062689, 030651, 139025, 028806, 009551, 12579...","[024316, 024617, 029453, 061685, 012181, 01357...","[138743, 138205, 028877, 141384, 014275, 06308...","[001690, 012141, 064768, 117768, 002176, 01090..."
2002-06-30,"[144998, 028806, 009551, 125794, 064979, 14720...","[138743, 024316, 121382, 029453, 012181, 03065...","[147579, 136725, 138205, 028877, 141384, 14555...","[001690, 012141, 064768, 117768, 002176, 01090..."
2003-06-30,"[144998, 028806, 009551, 025964, 125794, 06497...","[138743, 024316, 029453, 010795, 143912, 02901...","[136725, 138205, 028877, 145552, 121382, 02461...","[001690, 012141, 064768, 117768, 002176, 01090..."
2004-06-30,"[009551, 125794, 147204, 061490, 008001, 06115...","[012181, 008214, 144998, 066326, 064857, 02880...","[138205, 028877, 024316, 121382, 149337, 14146...","[001690, 012141, 064768, 117768, 002176, 01090..."
2005-06-30,"[009551, 125794, 061490, 148170, 017199, 02429...","[012181, 141277, 061655, 144998, 066326, 06485...","[126136, 023812, 138205, 028877, 162887, 14138...","[001690, 012141, 160329, 064768, 117768, 00217..."
2006-06-30,"[062965, 009551, 125794, 061490, 028384, 01719...","[012181, 141277, 008214, 144998, 031255, 13390...","[126136, 028877, 162887, 141384, 141460, 00385...","[001690, 012141, 160329, 064768, 117768, 00217..."
2007-06-30,"[062965, 017199, 012482, 002578, 014113, 02499...","[012181, 141277, 144998, 009551, 011670, 12579...","[028877, 162887, 141460, 029359, 160888, 01078...","[001690, 012141, 160329, 064768, 117768, 00217..."
2008-06-30,"[062965, 061711, 017199, 002578, 014113, 02499...","[118122, 141277, 064175, 144998, 064857, 02880...","[126136, 162887, 029453, 029359, 179216, 01078...","[001690, 012141, 160329, 064768, 117768, 00217..."
2009-06-30,"[126136, 062965, 164363, 061711, 002337, 17603...","[118122, 141277, 016477, 144998, 028806, 06135...","[162887, 165746, 029453, 029359, 066065, 17921...","[001690, 012141, 160329, 064768, 117768, 00217..."
2010-06-30,"[061711, 017199, 002337, 002578, 065905, 02465...","[118122, 125604, 012181, 144998, 028806, 00955...","[005073, 029453, 029359, 010789, 137573, 16303...","[001690, 012141, 160329, 064768, 184996, 11776..."
2011-06-30,"[175269, 061711, 178073, 162400, 017199, 00257...","[118122, 125604, 144998, 028806, 009551, 02079...","[160888, 264265, 163036, 013619, 119316, 01218...","[001690, 012141, 160329, 064768, 184996, 11776..."
2012-06-30,"[163118, 175269, 162400, 017199, 002578, 02244...","[125604, 160770, 064857, 028806, 009551, 02079...","[187450, 185355, 264265, 163036, 119316, 01218...","[001690, 012141, 160329, 064768, 184996, 17061..."
2013-06-30,"[163118, 175269, 018009, 002578, 025088, 18352...","[125604, 160770, 028806, 009551, 031255, 00438...","[187450, 185355, 163036, 012181, 105661, 01611...","[001690, 012141, 160329, 064768, 184996, 17061..."
2014-06-30,"[163118, 016125, 002578, 025088, 129441, 06170...","[175269, 020096, 004384, 162146, 178073, 14817...","[187450, 020116, 163036, 012181, 105661, 01807...","[001690, 012141, 160329, 064768, 184996, 17061..."
2015-06-30,"[163118, 016125, 002578, 166218, 025088, 12944...","[175269, 018875, 020096, 004384, 117829, 16214...","[187450, 021808, 125604, 105661, 003107, 01659...","[001690, 012141, 160329, 064768, 184996, 17061..."
2016-06-30,"[163118, 012485, 026567, 061153, 014793, 00257...","[187450, 160770, 009551, 018562, 175269, 01887...","[021808, 125604, 024249, 016597, 018899, 01990...","[001690, 012141, 160329, 064768, 184996, 17061..."
2017-06-30,"[163118, 026567, 004384, 061153, 002578, 02508...","[187450, 018899, 160770, 028806, 028670, 00955...","[030999, 125604, 061655, 024176, 027155, 16475...","[001690, 012141, 160329, 064768, 184996, 17061..."
2018-06-30,"[163118, 002578, 106897, 008611, 012987, 18565...","[009551, 004384, 028012, 003105, 148170, 18885...","[187450, 125604, 061655, 016597, 135484, 02324...","[001690, 012141, 160329, 064768, 184996, 17061..."
2019-06-30,"[163118, 025430, 002578, 008092, 106897, 01298...","[004384, 028012, 148170, 004367, 179598, 13764...","[125604, 145049, 061655, 027155, 135484, 00955...","[001690, 012141, 160329, 064768, 184996, 17061..."
2020-06-30,"[163118, 135484, 002578, 010877, 106897, 06630...","[027786, 021431, 004384, 155393, 148170, 13764...","[177637, 005600, 145049, 018465, 003964, 01552...","[001690, 012141, 160329, 064768, 184996, 17061..."
2021-06-30,"[011925, 006385, 065030, 063122, 022761, 00469...","[065286, 029914, 014010, 025852, 066301, 06170...","[024233, 019855, 016848, 018572, 122915, 18460...","[001690, 012141, 160329, 064768, 184996, 17061..."

In [29]:
BVMV = bv/mktcap
BVMV

,001003,001004,001009,001011,001012,001013,001015,001016,001017,001019,...,315887,316056,317260,317264,317427,318728,326688,327451,328032,328795
date,,,,,,,,,,,,,,,,,,,,,
1986-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-01-31,1.208100,NaN,NaN,1.572906,NaN,NaN,NaN,NaN,NaN,0.994688,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-02-28,1.279165,NaN,NaN,1.747673,NaN,NaN,NaN,NaN,1.589550,0.987733,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-03-31,1.279165,NaN,NaN,1.572906,NaN,NaN,NaN,NaN,1.502848,0.980873,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-04-30,1.359113,NaN,NaN,1.747673,NaN,NaN,NaN,NaN,1.620718,0.980873,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
HML = bv/mktcap
HML = HML.groupby(HML.index.month).get_group(6)

In [22]:
HML_q = HML.rank(1, 'first').apply(lambda x: pd.qcut(x, q=10, labels = range(1,11)) if not x.isnull().all() else x, 1)
HML_port = HML_q.apply(lambda x: portfolio_groups(x, range(1,11)), axis=1, result_type = 'expand')
HML_port.columns = ['HML{}'.format(i) for i in range(1,11)]
HML_port

,HML1,HML2,HML3,HML4,HML5,HML6,HML7,HML8,HML9,HML10
date,,,,,,,,,,
1987-06-30,"[001065, 001078, 001112, 001169, 001181, 00118...","[001028, 001050, 001073, 001091, 001097, 00112...","[001004, 001240, 001254, 001374, 001392, 00143...","[001020, 001023, 001054, 001055, 001124, 00115...","[001003, 001019, 001034, 001072, 001111, 00112...","[001037, 001056, 001094, 001099, 001104, 00114...","[001017, 001076, 001113, 001120, 001318, 00133...","[001011, 001045, 001075, 001117, 001130, 00115...","[001036, 001038, 001082, 001108, 001109, 00114...","[001058, 001126, 001177, 001178, 001194, 00122..."
1988-06-30,"[001050, 001091, 001130, 001169, 001171, 00118...","[001013, 001020, 001023, 001065, 001078, 00111...","[001004, 001054, 001121, 001161, 001201, 00125...","[001097, 001138, 001151, 001209, 001222, 00136...","[001016, 001019, 001028, 001037, 001094, 00110...","[001003, 001055, 001056, 001072, 001099, 00112...","[001009, 001034, 001036, 001076, 001081, 00110...","[001011, 001017, 001045, 001073, 001075, 00109...","[001012, 001043, 001082, 001108, 001126, 00114...","[001038, 001058, 001103, 001148, 001177, 00117..."
1989-06-30,"[001065, 001078, 001115, 001130, 001163, 00116...","[001013, 001023, 001112, 001181, 001239, 00124...","[001004, 001009, 001011, 001037, 001050, 00112...","[001054, 001097, 001109, 001121, 001186, 00122...","[001016, 001019, 001020, 001034, 001094, 00109...","[001072, 001073, 001098, 001111, 001120, 00116...","[001036, 001076, 001104, 001117, 001126, 00114...","[001028, 001043, 001045, 001055, 001056, 00108...","[001012, 001017, 001038, 001082, 001108, 00122...","[001003, 001058, 001075, 001103, 001148, 00117..."
1990-06-30,"[001065, 001078, 001163, 001244, 001259, 00126...","[001013, 001037, 001112, 001137, 001239, 00124...","[001073, 001117, 001128, 001138, 001141, 00117...","[001004, 001011, 001034, 001055, 001072, 00111...","[001009, 001019, 001020, 001050, 001054, 00109...","[001097, 001104, 001109, 001111, 001234, 00124...","[001036, 001045, 001076, 001081, 001098, 00115...","[001012, 001038, 001056, 001095, 001173, 00120...","[001017, 001028, 001043, 001075, 001082, 00110...","[001003, 001058, 001103, 001148, 001177, 00117..."
1991-06-30,"[001050, 001078, 001163, 001244, 001259, 00132...","[001013, 001037, 001197, 001240, 001266, 00144...","[001055, 001073, 001109, 001115, 001137, 00116...","[001072, 001128, 001138, 001151, 001161, 00118...","[001004, 001011, 001019, 001020, 001034, 00109...","[001009, 001111, 001117, 001121, 001141, 00123...","[001054, 001065, 001076, 001081, 001097, 00109...","[001012, 001036, 001038, 001045, 001098, 00122...","[001017, 001028, 001043, 001056, 001075, 00108...","[001003, 001058, 001148, 001177, 001178, 00119..."
1992-06-30,"[001073, 001078, 001163, 001259, 001359, 00144...","[001037, 001050, 001115, 001181, 001240, 00124...","[001013, 001137, 001203, 001264, 001331, 00141...","[001009, 001164, 001171, 001186, 001197, 00120...","[001011, 001034, 001054, 001055, 001094, 00110...","[001004, 001019, 001076, 001138, 001141, 00115...","[001065, 001081, 001099, 001104, 001117, 00117...","[001036, 001038, 001045, 001075, 001097, 00109...","[001017, 001056, 001082, 001154, 001178, 00123...","[001028, 001043, 001058, 001095, 001148, 00115..."
1993-06-30,"[001050, 001163, 001228, 001244, 001259, 00131...","[001013, 001037, 001078, 001115, 001181, 00118...","[001011, 001034, 001073, 001137, 001164, 00117...","[001009, 001111, 001161, 001239, 001266, 00127...","[001094, 001109, 001128, 001203, 001209, 00123...","[001054, 001076, 001099, 001151, 001165, 00119...","[001004, 001019, 001055, 001098, 001117, 00113...","[001036, 001038, 001056, 001075, 001081, 00109...","[001017, 001045, 001082, 001097, 001108, 00115...","[001043, 001058, 001148, 001155, 001177, 00117..."
1994-06-30,"[001011, 001013, 001163, 001181, 001259, 00131...","[001037, 001078, 001186, 001228, 001240, 00124...","[001050, 001128, 001138, 001210, 001278, 00128...","[001009, 001111, 001115, 001137, 001161, 00126...","[001054, 001073, 001076, 001094, 001099, 00115...","[001034, 001056, 001141, 001213, 001226, 00125...","[001004, 001019, 001036, 001055, 001081, 00109...","[001017, 001038, 001043, 001097, 001104, 00110...","[001045, 001075, 001082, 001154, 001230, 00127...","[001058, 001148, 001177, 001194, 001245, 00127..."
1995-06-30,"[001013, 001050, 001078, 001163, 001244, 00125...","[001011, 001099, 001228, 001257, 001281, 00132...","[001037, 001115, 001128, 001137, 001138, 00116...","[001095, 001098, 001111, 001151, 001164, 00118...","[001017, 001054, 001076, 001094, 001109, 00118...","[001004, 001009, 001034, 001036, 001056, 00107...","[001019, 001038, 001055, 001121, 001173, 00123...","[001045, 001075, 001097, 001104, 001117, 00121...","[001043, 001082, 001108, 001154, 001230, 00143...","[001148, 001177, 001194, 001197, 001245, 00127..."
1996-06-30,"[001259, 001311, 001328, 001441, 001602, 00165...","[001011, 001013, 001037, 001073, 001078, 00113...","[001050, 001072, 001095, 001111, 001115, 00113...","[001076, 001098, 001109, 001151, 001164, 00118...","[001038, 001108, 001203, 001209, 001210, 00123...","[001004, 001017, 001019, 001056, 001094, 00118...","[001034, 001036, 001081, 001099, 001161, 00117...","[001045, 001055, 001075, 001104, 001117, 00112...","[001097, 001154, 001165, 001235, 001331, 00139...","[001009, 001043, 001082, 001148, 001177, 00119..."
1997-06-30,"[001013, 001078, 001244, 001259, 001495, 00160...","[001037, 001050, 001072, 001073, 001173, 00127...","[001108, 001111, 001115, 001151, 001228, 00123...","[001076, 001095, 001098, 001161, 001164, 00120...","[001004, 001019, 001210, 001226, 001265, 00126...","[001056, 001094, 001104, 001109, 001186, 00123...","[001034, 001036, 001081, 001099, 001121, 00118...","[001038, 001045, 001055, 001075, 001117, 00127...","[001082, 001097, 001148, 001154, 001230, 00123...","[001043, 001165, 001177, 001194, 001250, 00132..."
1998-06-30,"[001013, 001078, 001244, 001259, 001441, 00149...","[001095, 001173, 001240, 001260, 001359, 00147...","[001019, 001037, 001076, 001115, 001164, 00125...","[001050, 001056, 001072, 001094, 001108, 00120...","[001004, 001226, 001265, 001266, 001278, 00141...","[001034, 001036, 001109, 001111, 001230, 00125...","[001045, 001075, 001161, 001186, 001228, 00123...","[001038, 001043, 001055, 001081, 001099, 00110...","[001097, 001148, 001154, 001372, 001378, 00139...","[001073, 001082, 001165, 001177, 001183, 00119..."
1999-06-30,"[001013, 001037, 001078, 001327, 001602, 00163...","[001173, 001244, 001308, 001334, 001359, 00147...","[001050, 001056, 001072, 001076, 001095, 00116...","[001019, 001034, 001111, 001203, 001209, 00123...","[001004, 001094, 001186, 001213, 001266, 00136...","[001099, 001109, 001115, 001161, 001210, 00122...","[001036, 001038, 001045, 001073, 001075, 00111...","[001081, 001097, 001108, 001121, 001154, 00123...","[001104, 001148, 001165, 001183, 001278, 00139...","[001043, 001082, 001177, 001194, 001263, 00129..."
2000-06-30,"[001013, 001259, 001441, 001602, 001632, 00170...","[001037, 001056, 001078, 001327, 001334, 00135...","[001034, 001072, 001115, 001161, 001173, 00124...","[001164, 001186, 001203, 001228, 001235, 00123...","[001019, 001076, 001094, 001095, 001099, 00120...","[001081, 001104, 001109, 001111, 001117, 00121...","[001004, 001050, 001075, 001154, 001210, 00123...","[001036, 001121, 001183, 001274, 001444, 00153...","[001038, 001045, 001082, 001097, 001148, 00124...","[001043, 001165, 001177, 001263, 001297, 00133..."
2001-06-30,"[001078, 001244, 001259, 001327, 001359, 00160...","[001037, 001056, 001111, 001173, 001478, 00163...","[001013, 001072, 001115, 001161, 001186, 00123...","[001019, 001076, 001099, 001209, 001228, 00128...","[001004, 001034, 001094, 001234, 001240, 00124...","[001036, 001075, 001095, 001104, 001109, 00116...","[001038, 001050, 001081, 001117, 001154, 00121...","[001045, 001097, 001165, 001246, 001382, 00144...","[001043, 001082, 001121, 001148, 001372, 00139...","[001177, 001183, 001263, 001278, 001297, 00133..."
2002-06-30,"[001111, 001173, 001259, 001359, 001478, 00151...","[001072, 001078, 001115, 001186, 001239, 00124...","[001019, 001056, 001076, 001154, 001209, 00126...","[001037, 001095, 001099, 001228, 001356, 00149...","[001013, 001094, 001104, 001234, 001240, 00124...","[001004, 001036, 001050, 001075, 001109, 00116...","[001034, 001038, 001081, 001117, 001210, 00127...","[001082, 001097, 001177, 001230, 001246, 00144...","[001045, 001121, 001148, 001372, 001393, 00139...","[001164, 001165, 001183, 001263, 001331, 00133..."
2003-06-30,"[001259, 001602, 001920, 001951, 002230, 00223...","[001078, 001173, 001478, 001518, 001632, 00166...","[001013, 001019, 001056, 001076, 001094, 00110...","[001072, 001095, 001209, 001266, 001281, 00131...","[001037, 001104, 001154, 001234, 001254, 00125...","[001034, 001213, 001228, 001238, 001240, 00124...","[001004, 001050, 001075, 001117, 001161, 00121...","[001038, 001081, 001097, 001121, 001177, 00123...","[001082, 001279, 001382, 001418, 001998, 00200...","[001045, 001164, 001165, 001183, 001263, 00133..."
2004-06-30,"[001259, 001632, 001878, 001920, 001951, 00210...","[001117, 001228, 001244, 001439, 001518, 00155...","[001013, 001056, 001076, 001078, 001094, 00110...","[001072, 001104, 001173, 001209, 001234, 00126...","[001281, 001300, 001308, 001318, 001363, 00141...","[001161, 001254, 001257, 001283, 001356, 00149...","[001004, 001034, 001154, 001213, 001240, 00124...","[001038, 001050, 001075, 001081, 001121, 00117...","[001082, 001097, 001164, 001230, 001279, 00138...","[001045, 001165, 001183, 001263, 001372, 00139..."
2005-06-30,"[001259, 001439, 001554, 001690, 001878, 00192...","[001078, 001104, 001111, 001228, 001523, 00158...","[001013, 001076, 001109, 001210, 001234, 00123...","[001072, 001094, 001117, 001186, 001209, 00126...","[001056, 001173, 001254, 001257, 001300, 00130...","[001161, 001283, 001618, 001634, 001641, 00165...","[001004, 001050, 001177, 001274, 001356, 00136...","[001034, 001038, 001075, 001121, 001164, 00118...","[001081, 001082, 001097, 001230, 001331, 00144...","[001045, 001165, 001263, 001372, 001382, 00139..."
2006-06-30,"[001259, 001439, 001682, 001690, 001878, 00195...","[001117, 001186, 001554, 001602, 001632, 00172...","[001050, 001078, 001104, 001111, 001239, 00130...","[001056, 001072, 001076, 001161, 001209, 00123...","[001013, 001109, 001173, 001210, 001283, 00136...","[001004, 001034, 001094, 001228, 001254, 00125...","[001243, 001279, 001327, 001363, 001380, 00138...","[001075, 001121, 001164, 001177, 001230, 00124...","[001045, 001082, 001097, 001331, 001441, 00148...","[001081, 001165, 001183, 001263, 001397, 00154..."
2007-06-30,"[001259, 001690, 001878, 001951, 002230, 00229...","[001050, 001111, 001186, 001439, 001539, 00163...","[001078, 001117, 001234, 001478, 001523, 00155...","[001056, 001072, 001076, 001104, 001173, 00120...","[001004, 001013, 001034, 001094, 001109, 00125...","[001210, 001239, 001243, 001254, 001279, 00130...","[001380, 001408, 001491, 001611, 001722, 00177...","[001075, 001097, 001121, 001161, 001177, 00124...","[001045, 001081, 001082, 001183, 001230, 00133...","[001165, 001263, 001397, 001545, 002002, 00203..."
2008-06-30,"[001111, 001186, 001439, 001682, 001690, 00186...","[001078, 001259, 001577, 001632, 001663, 00170...","[001056, 001209, 001228, 001234, 001239, 00132...","[001076, 001104, 001243, 001300, 001318, 00149...","[001013, 001050, 001072, 001094, 001210, 00125...","[001034, 001117, 001254, 001308, 001356, 00140...","[001121, 001173, 001274, 001440, 001449, 00149...","[001004, 001075, 001082, 001097, 001109, 00116...","[001081, 001183, 001230, 001331, 001414, 00152...","[001045, 001165, 001263, 001382, 001397, 00144..."
2009-06-30,"[001111, 001439, 001663, 001682, 001690, 00172...","[001078, 001186, 001234, 001239, 001259, 00152...","[001034, 001076, 001173, 001209, 001327, 00147...","[001072, 001094, 001257, 001266, 001593, 00163...","[001104, 001117, 001210, 001246, 001300, 00138...","[001004, 001013, 001050, 001228, 001254, 00127...","[001075, 001097, 001121, 001161, 001177, 00135...","[001082, 001230, 001308, 001393, 001414, 00144...","[001109, 001331, 001526, 001545, 002150, 00229...","[001045, 001183, 001263, 001367, 001382, 00139..."
2010-06-30,"[001259, 001682, 001690, 001968, 001979, 00210...","[001186, 001234, 001327, 001439, 001554, 00163...","[001078, 001239, 001478, 001523, 001598, 00160...","[001072, 001076, 001117, 001209, 001562, 00165...","[001050, 001104, 001210, 001257, 001266, 00130...","[001013, 001094, 001161, 001246, 001254, 00138...","[001004, 001173, 001228, 001274, 001408, 00144...","[001075, 001082, 001097, 001121, 001177, 00123...","[001045, 001109, 001308, 001382, 001414, 00152...","[001263, 001331, 001367, 001397, 001487, 00154..."
2011-06-30,"[001682, 001690, 001951, 001979, 002222, 00299...","[001234, 001259, 001327, 001554, 001632, 00172...","[001186, 001209, 001239, 001562, 001598, 00170...","[001050, 001072, 001076, 001078, 001228, 00125...","[001161, 001266, 001678, 001712, 001820, 00192...","[001013, 001210, 001254, 001380, 001408, 00141...","[001004, 001082, 001094, 001104, 001117, 00117...","[001075, 001097, 001121, 001279, 001356, 00139...","[001382, 001414, 001449, 001526, 001533, 00155...","[001045, 001263, 001331, 001487, 001545, 00161..."
2012-06-30,"[001259, 001690, 001979, 002435, 002615, 00317...","[001234, 001239, 001327, 001523, 001585, 00163...","[001050, 001078, 001186, 001408, 001439, 00155...","[001076, 001209, 001257, 001266, 001300, 00159...","[001013, 001094, 001161, 001254, 001274, 00163...","[001072, 001104, 001117, 001173, 001210, 00141...","[001075, 001082, 001121, 001228, 001230, 00130...","[001004, 001097, 001177, 001279, 001356, 00136...","[001331, 001397, 001414, 001449, 001487, 00149...","[001045, 001263, 001526, 001545, 001611, 00200..."
2013-06-30,"[001259, 001728, 001979, 002435, 003170, 00336...","[001050, 001234, 001439, 001562, 001632, 00182...","[001266, 001300, 001327, 001554, 001585, 00159...","[001076, 001094, 001117, 001173, 001209, 00140...","[001186, 001254, 001257, 001533, 001650, 00168...","[001072, 001078, 001121, 001161, 001210, 00123...","[001075, 001104, 001177, 001380, 001393, 00144...","[001004, 001097, 001228, 001274, 001331, 00136...","[001356, 001414, 001449, 001487, 001496, 00152...","[001045, 001263, 001397, 001545, 001611, 00200..."
2014-06-30,"[001259, 002435, 003170, 003382, 003691, 00404...","[001234, 001327, 001439, 001632, 001690, 00172...","[001554, 001562, 001598, 001635, 001650, 00168...","[001076, 001078, 001117, 001173, 001186, 00120...","[001050, 001094, 001230, 001682, 001706, 00174...","[001072, 001104, 001210, 001254, 001393, 00158...","[001045, 001121, 001161, 001177, 001380, 00141...","[001004, 001075, 001097, 001228, 001356, 00138...","[001274, 001331, 001414, 001449, 001487, 00149...","[001263, 001397, 001526, 001545, 002002, 00201..."
2015-06-30,"[001327, 002312, 002435, 003288, 003369, 00338...","[001234, 001632, 001686, 001690, 001823, 00196...","[001078, 001117, 001209, 001266, 001300, 00155...","[001094, 001230, 001254, 001257, 001408, 00153...","[001072, 001076, 001186, 001210, 001393, 00143...","[001004, 001050, 001104, 001177, 001410, 00158...","[001045, 001121, 001161, 001380, 001447, 00165...","[001075, 001274, 001356, 001440, 001613, 00161...","[001097, 001228, 001414, 001449, 001487, 00149...","[001263, 001397, 001496, 001526, 001545, 00194..."
2016-06-30,"[001234, 002044, 002403, 002435, 002942, 00312...","[001327, 001562, 001632, 001686, 001878, 00196...","[001078, 001117, 001186, 001209, 001257, 00130...","[001094, 001161, 001230, 001439, 001678, 00182...","[001072, 001177, 001210, 001254, 001393, 00141...","[001075, 001076, 001104, 001121, 001650, 00172...","[001004, 001050, 001266, 001380, 001440, 00165...","[001045, 001097, 001228, 001274, 001356, 00141...","[001487, 001526, 001559, 001860, 001949, 00200...","[001397, 001545, 001951, 002002, 002019, 00233..."
2017-06-30,"[001234, 001327, 001878, 002044, 002942, 00315...","[001161, 001632, 001704, 001968, 001979, 00226...","[001078, 001209, 001300, 001562, 001598, 00160...","[001117, 001186, 001257, 001439, 001554, 00158...","[001072, 001076, 001104, 001230, 001410, 00165...","[001004, 001121, 001177, 001210, 001393, 00167...","[001045, 001050, 001075, 001254, 001266, 00138...","[001094, 001274, 001356, 001414, 001559, 00161...","[001097, 001228, 001449, 002005, 002019, 00236...","[001397, 001487, 001526, 001545, 001860, 00194..."
2018-06-30,"[001234, 001878, 002735, 002942, 002960, 00404...","[001161, 001327, 001562, 001968, 001979, 00204...","[001209, 001300, 001439, 001598, 001633, 00165...","[001078, 001186, 001585, 001602, 001632, 00168...","[001004, 001072, 001076, 001117, 001177, 00125...","[001210, 001230, 001254, 001380, 001678, 00174...","[001050, 001075, 001104, 001121, 001266, 00139...","[001045, 001097, 001274, 001414, 001447, 00165...","[001449, 001545, 001559, 001613, 001661, 00186...","[001094, 001228, 001397, 001487, 001526, 00200..."
2019-06-30,[],[],[],[],[],[],[],[],[],[]
2020-06-30,[],[],[],[],[],[],[],[],[],[]
2021-06-30,[],[],[],[],[],[],[],[],[],[]

### 2 X 3으로 만들기

In [23]:
def makethree(db, position):
    return [db[db.columns[position]] + db[db.columns[position+1]]+db[db.columns[position+2]]]

In [24]:
def makefour(db, position):
    return [db[db.columns[position]] + db[db.columns[position+1]]+db[db.columns[position+2]]+db[db.columns[position+3]]]

In [25]:
SMB_2 = pd.concat([mktcap_port['MktCap1'], pd.DataFrame(makethree(mktcap_port, 1)).T], axis=1)
SMB_2.columns = ['Big', 'Small']
SMB_2

,Big,Small
date,,
1987-06-30,"[011811, 008644, 012140, 009063, 010991, 00955...","[013421, 014275, 012441, 013510, 015417, 00556..."
1988-06-30,"[014477, 017120, 011811, 008644, 012140, 00906...","[002710, 014275, 001327, 013510, 015417, 00556..."
1989-06-30,"[014477, 015414, 011811, 008644, 009063, 01624...","[002710, 017120, 014275, 012850, 001327, 01351..."
1990-06-30,"[014477, 011811, 012140, 014561, 009273, 00955...","[014275, 012850, 001327, 013510, 015414, 01541..."
1991-06-30,"[014561, 009273, 009551, 003969, 008512, 02154...","[024316, 001327, 013510, 012459, 005567, 02090..."
1992-06-30,"[024316, 008644, 014561, 009273, 009551, 00959...","[001327, 013510, 012459, 005567, 020904, 01357..."
1993-06-30,"[012459, 003504, 025274, 014561, 009551, 00959...","[024316, 024468, 001327, 013510, 005567, 02090..."
1994-06-30,"[025274, 014561, 028806, 006223, 009551, 00959...","[028877, 024316, 024468, 001327, 030098, 00350..."
1995-06-30,"[024316, 025274, 028806, 009551, 020791, 00851...","[028877, 030662, 010789, 003504, 005567, 02090..."
1996-06-30,"[024316, 012181, 028806, 030612, 020791, 02563...","[028877, 024617, 061420, 010789, 013570, 06165..."
1997-06-30,"[024316, 012181, 028806, 009551, 014027, 03061...","[028877, 029453, 001327, 061420, 010789, 06296..."
1998-06-30,"[028877, 028806, 009551, 014027, 030612, 02840...","[024316, 029453, 064630, 061685, 012181, 01357..."
1999-06-30,"[028806, 009551, 014027, 030612, 028408, 06171...","[028877, 024316, 029453, 020904, 061685, 01218..."
2000-06-30,"[062689, 030651, 028806, 030612, 125794, 02951...","[028877, 024316, 024617, 029453, 064410, 06296..."
2001-06-30,"[062689, 030651, 139025, 028806, 009551, 12579...","[024316, 024617, 029453, 061685, 012181, 01357..."
2002-06-30,"[144998, 028806, 009551, 125794, 064979, 14720...","[138743, 024316, 121382, 029453, 012181, 03065..."
2003-06-30,"[144998, 028806, 009551, 025964, 125794, 06497...","[138743, 024316, 029453, 010795, 143912, 02901..."
2004-06-30,"[009551, 125794, 147204, 061490, 008001, 06115...","[012181, 008214, 144998, 066326, 064857, 02880..."
2005-06-30,"[009551, 125794, 061490, 148170, 017199, 02429...","[012181, 141277, 061655, 144998, 066326, 06485..."
2006-06-30,"[062965, 009551, 125794, 061490, 028384, 01719...","[012181, 141277, 008214, 144998, 031255, 13390..."
2007-06-30,"[062965, 017199, 012482, 002578, 014113, 02499...","[012181, 141277, 144998, 009551, 011670, 12579..."
2008-06-30,"[062965, 061711, 017199, 002578, 014113, 02499...","[118122, 141277, 064175, 144998, 064857, 02880..."
2009-06-30,"[126136, 062965, 164363, 061711, 002337, 17603...","[118122, 141277, 016477, 144998, 028806, 06135..."
2010-06-30,"[061711, 017199, 002337, 002578, 065905, 02465...","[118122, 125604, 012181, 144998, 028806, 00955..."
2011-06-30,"[175269, 061711, 178073, 162400, 017199, 00257...","[118122, 125604, 144998, 028806, 009551, 02079..."
2012-06-30,"[163118, 175269, 162400, 017199, 002578, 02244...","[125604, 160770, 064857, 028806, 009551, 02079..."
2013-06-30,"[163118, 175269, 018009, 002578, 025088, 18352...","[125604, 160770, 028806, 009551, 031255, 00438..."
2014-06-30,"[163118, 016125, 002578, 025088, 129441, 06170...","[175269, 020096, 004384, 162146, 178073, 14817..."
2015-06-30,"[163118, 016125, 002578, 166218, 025088, 12944...","[175269, 018875, 020096, 004384, 117829, 16214..."
2016-06-30,"[163118, 012485, 026567, 061153, 014793, 00257...","[187450, 160770, 009551, 018562, 175269, 01887..."
2017-06-30,"[163118, 026567, 004384, 061153, 002578, 02508...","[187450, 018899, 160770, 028806, 028670, 00955..."
2018-06-30,"[163118, 002578, 106897, 008611, 012987, 18565...","[009551, 004384, 028012, 003105, 148170, 18885..."
2019-06-30,"[163118, 025430, 002578, 008092, 106897, 01298...","[004384, 028012, 148170, 004367, 179598, 13764..."
2020-06-30,"[163118, 135484, 002578, 010877, 106897, 06630...","[027786, 021431, 004384, 155393, 148170, 13764..."
2021-06-30,"[011925, 006385, 065030, 063122, 022761, 00469...","[065286, 029914, 014010, 025852, 066301, 06170..."

In [28]:
HML_3 = pd.concat([pd.DataFrame(makethree(HML_port,0)).T, pd.DataFrame(makefour(HML_port, 3)).T, pd.DataFrame(makethree(HML_port,7)).T], axis=1)
HML_3.columns = ['High', 'Medium', 'Low']
HML_3

,High,Medium,Low
date,,,
1987-06-30,"[001065, 001078, 001112, 001169, 001181, 00118...","[001020, 001023, 001054, 001055, 001124, 00115...","[001011, 001045, 001075, 001117, 001130, 00115..."
1988-06-30,"[001050, 001091, 001130, 001169, 001171, 00118...","[001097, 001138, 001151, 001209, 001222, 00136...","[001011, 001017, 001045, 001073, 001075, 00109..."
1989-06-30,"[001065, 001078, 001115, 001130, 001163, 00116...","[001054, 001097, 001109, 001121, 001186, 00122...","[001028, 001043, 001045, 001055, 001056, 00108..."
1990-06-30,"[001065, 001078, 001163, 001244, 001259, 00126...","[001004, 001011, 001034, 001055, 001072, 00111...","[001012, 001038, 001056, 001095, 001173, 00120..."
1991-06-30,"[001050, 001078, 001163, 001244, 001259, 00132...","[001072, 001128, 001138, 001151, 001161, 00118...","[001012, 001036, 001038, 001045, 001098, 00122..."
1992-06-30,"[001073, 001078, 001163, 001259, 001359, 00144...","[001009, 001164, 001171, 001186, 001197, 00120...","[001036, 001038, 001045, 001075, 001097, 00109..."
1993-06-30,"[001050, 001163, 001228, 001244, 001259, 00131...","[001009, 001111, 001161, 001239, 001266, 00127...","[001036, 001038, 001056, 001075, 001081, 00109..."
1994-06-30,"[001011, 001013, 001163, 001181, 001259, 00131...","[001009, 001111, 001115, 001137, 001161, 00126...","[001017, 001038, 001043, 001097, 001104, 00110..."
1995-06-30,"[001013, 001050, 001078, 001163, 001244, 00125...","[001095, 001098, 001111, 001151, 001164, 00118...","[001045, 001075, 001097, 001104, 001117, 00121..."
1996-06-30,"[001259, 001311, 001328, 001441, 001602, 00165...","[001076, 001098, 001109, 001151, 001164, 00118...","[001045, 001055, 001075, 001104, 001117, 00112..."
1997-06-30,"[001013, 001078, 001244, 001259, 001495, 00160...","[001076, 001095, 001098, 001161, 001164, 00120...","[001038, 001045, 001055, 001075, 001117, 00127..."
1998-06-30,"[001013, 001078, 001244, 001259, 001441, 00149...","[001050, 001056, 001072, 001094, 001108, 00120...","[001038, 001043, 001055, 001081, 001099, 00110..."
1999-06-30,"[001013, 001037, 001078, 001327, 001602, 00163...","[001019, 001034, 001111, 001203, 001209, 00123...","[001081, 001097, 001108, 001121, 001154, 00123..."
2000-06-30,"[001013, 001259, 001441, 001602, 001632, 00170...","[001164, 001186, 001203, 001228, 001235, 00123...","[001036, 001121, 001183, 001274, 001444, 00153..."
2001-06-30,"[001078, 001244, 001259, 001327, 001359, 00160...","[001019, 001076, 001099, 001209, 001228, 00128...","[001045, 001097, 001165, 001246, 001382, 00144..."
2002-06-30,"[001111, 001173, 001259, 001359, 001478, 00151...","[001037, 001095, 001099, 001228, 001356, 00149...","[001082, 001097, 001177, 001230, 001246, 00144..."
2003-06-30,"[001259, 001602, 001920, 001951, 002230, 00223...","[001072, 001095, 001209, 001266, 001281, 00131...","[001038, 001081, 001097, 001121, 001177, 00123..."
2004-06-30,"[001259, 001632, 001878, 001920, 001951, 00210...","[001072, 001104, 001173, 001209, 001234, 00126...","[001038, 001050, 001075, 001081, 001121, 00117..."
2005-06-30,"[001259, 001439, 001554, 001690, 001878, 00192...","[001072, 001094, 001117, 001186, 001209, 00126...","[001034, 001038, 001075, 001121, 001164, 00118..."
2006-06-30,"[001259, 001439, 001682, 001690, 001878, 00195...","[001056, 001072, 001076, 001161, 001209, 00123...","[001075, 001121, 001164, 001177, 001230, 00124..."
2007-06-30,"[001259, 001690, 001878, 001951, 002230, 00229...","[001056, 001072, 001076, 001104, 001173, 00120...","[001075, 001097, 001121, 001161, 001177, 00124..."
2008-06-30,"[001111, 001186, 001439, 001682, 001690, 00186...","[001076, 001104, 001243, 001300, 001318, 00149...","[001004, 001075, 001082, 001097, 001109, 00116..."
2009-06-30,"[001111, 001439, 001663, 001682, 001690, 00172...","[001072, 001094, 001257, 001266, 001593, 00163...","[001082, 001230, 001308, 001393, 001414, 00144..."
2010-06-30,"[001259, 001682, 001690, 001968, 001979, 00210...","[001072, 001076, 001117, 001209, 001562, 00165...","[001075, 001082, 001097, 001121, 001177, 00123..."
2011-06-30,"[001682, 001690, 001951, 001979, 002222, 00299...","[001050, 001072, 001076, 001078, 001228, 00125...","[001075, 001097, 001121, 001279, 001356, 00139..."
2012-06-30,"[001259, 001690, 001979, 002435, 002615, 00317...","[001076, 001209, 001257, 001266, 001300, 00159...","[001004, 001097, 001177, 001279, 001356, 00136..."
2013-06-30,"[001259, 001728, 001979, 002435, 003170, 00336...","[001076, 001094, 001117, 001173, 001209, 00140...","[001004, 001097, 001228, 001274, 001331, 00136..."
2014-06-30,"[001259, 002435, 003170, 003382, 003691, 00404...","[001076, 001078, 001117, 001173, 001186, 00120...","[001004, 001075, 001097, 001228, 001356, 00138..."
2015-06-30,"[001327, 002312, 002435, 003288, 003369, 00338...","[001094, 001230, 001254, 001257, 001408, 00153...","[001075, 001274, 001356, 001440, 001613, 00161..."
2016-06-30,"[001234, 002044, 002403, 002435, 002942, 00312...","[001094, 001161, 001230, 001439, 001678, 00182...","[001045, 001097, 001228, 001274, 001356, 00141..."
2017-06-30,"[001234, 001327, 001878, 002044, 002942, 00315...","[001117, 001186, 001257, 001439, 001554, 00158...","[001094, 001274, 001356, 001414, 001559, 00161..."
2018-06-30,"[001234, 001878, 002735, 002942, 002960, 00404...","[001078, 001186, 001585, 001602, 001632, 00168...","[001045, 001097, 001274, 001414, 001447, 00165..."
2019-06-30,[],[],[]
2020-06-30,[],[],[]
2021-06-30,[],[],[]

### 월별 price데이터가 없는 관계로.... 수익률은 mktcap으로 계산
먼저 windorize해서 위아래 5% 아웃라이어 없애기     
매월마다 팩터별 equally weighted 포트폴리오의 수익률을 계산 후 1/3*(small-big) 1/2*(high-low)한다

In [91]:
SMB_2_12m = pd.DataFrame(np.repeat(SMB_2.values, 12, axis=0), columns=SMB_2.columns)[:-5]
SMB_2_12m.index = mktcap.loc['1987-06-30':,:].index
SMB_2_12m

,Big,Small
date,,
1987-06-30,"[011811, 008644, 012140, 009063, 010991, 00955...","[013421, 014275, 012441, 013510, 015417, 00556..."
1987-07-31,"[011811, 008644, 012140, 009063, 010991, 00955...","[013421, 014275, 012441, 013510, 015417, 00556..."
1987-08-31,"[011811, 008644, 012140, 009063, 010991, 00955...","[013421, 014275, 012441, 013510, 015417, 00556..."
1987-09-30,"[011811, 008644, 012140, 009063, 010991, 00955...","[013421, 014275, 012441, 013510, 015417, 00556..."
1987-10-31,"[011811, 008644, 012140, 009063, 010991, 00955...","[013421, 014275, 012441, 013510, 015417, 00556..."
...,...,...
2021-08-31,"[011925, 006385, 065030, 063122, 022761, 00469...","[065286, 029914, 014010, 025852, 066301, 06170..."
2021-09-30,"[011925, 006385, 065030, 063122, 022761, 00469...","[065286, 029914, 014010, 025852, 066301, 06170..."
2021-10-31,"[011925, 006385, 065030, 063122, 022761, 00469...","[065286, 029914, 014010, 025852, 066301, 06170..."
2021-11-30,"[011925, 006385, 065030, 063122, 022761, 00469...","[065286, 029914, 014010, 025852, 066301, 06170..."
2021-12-31,"[011925, 006385, 065030, 063122, 022761, 00469...","[065286, 029914, 014010, 025852, 066301, 06170..."

In [381]:
mc_pct = mktcap.pct_change()
mc_pct

,001690,012141,160329,064768,184996,170617,117768,002176,010903,002968,...,294007,296318,296753,296944,297209,298092,311524,314866,317260,328032
date,,,,,,,,,,,,,,,,,,,,,
1986-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-01-31,0.370370,0.515544,NaN,NaN,NaN,NaN,NaN,0.099291,-0.164179,0.109467,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-02-28,0.261261,0.049573,NaN,NaN,NaN,NaN,NaN,0.083871,0.089286,-0.008000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-03-31,-0.059967,0.267957,NaN,NaN,NaN,NaN,NaN,0.047619,0.037419,-0.044084,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-04-30,0.228682,0.074936,NaN,NaN,NaN,NaN,NaN,-0.039773,-0.365079,-0.028571,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-31,0.040930,0.059563,0.074009,0.043034,0.070605,0.064777,0.148008,0.026259,0.009825,0.053828,...,-0.087688,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
2021-09-30,-0.075363,-0.067237,-0.080258,-0.051648,0.075466,-0.115855,-0.074559,-0.055204,-0.062326,0.012118,...,0.000000,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
2021-10-31,0.058657,0.176291,0.107499,0.026602,0.436530,-0.046613,0.237134,0.052319,0.178456,0.037876,...,0.000000,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
2021-11-30,0.103471,-0.003106,-0.041531,0.039924,0.027612,0.002751,0.278054,-0.037020,-0.035290,-0.065101,...,0.000000,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
2021-12-31,0.074229,0.017333,0.020821,-0.049252,-0.076855,0.036646,-0.099920,0.081046,0.130386,-0.003022,...,0.000000,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0

In [113]:
SMB_r = pd.DataFrame(index=SMB_2_12m.index, columns=SMB_2.columns)
r_big = []
r_small = []
for date in SMB_2_12m.index:
    r_big.append(mc_pct.loc[date, SMB_2_12m.loc[date, 'Big']].mean())
    r_small.append(mc_pct.loc[date, SMB_2_12m.loc[date, 'Small']].mean())
SMB_r['Big']= r_big
SMB_r['Small'] = r_small
SMB_r

                  Big     Small
date
1987-06-30   0.020958  0.054125
1987-07-31   0.056556  0.033870
1987-08-31   0.000752  0.024223
1987-09-30   0.039124 -0.006689
1987-10-31  -0.258287 -0.274785
...               ...       ...
2021-08-31   0.296515  0.004905
2021-09-30  29.996654 -0.000988
2021-10-31  10.840461  0.010272
2021-11-30   0.609817 -0.015047
2021-12-31   2.173414  0.002324

[415 rows x 2 columns]

In [114]:
SMB_r['Diff'] = 1/3*(SMB_r['Big'] - SMB_r['Small'])

In [115]:
HML_3_12m = pd.DataFrame(np.repeat(HML_3.values, 12, axis=0), columns=HML_3.columns)[:-5]
HML_3_12m.index = mktcap.loc['1987-06-30':,:].index
HML_3_12m

,High,Medium,Low
date,,,
1987-06-30,"[001065, 001078, 001112, 001169, 001181, 00118...","[001020, 001023, 001054, 001055, 001124, 00115...","[001011, 001045, 001075, 001117, 001130, 00115..."
1987-07-31,"[001065, 001078, 001112, 001169, 001181, 00118...","[001020, 001023, 001054, 001055, 001124, 00115...","[001011, 001045, 001075, 001117, 001130, 00115..."
1987-08-31,"[001065, 001078, 001112, 001169, 001181, 00118...","[001020, 001023, 001054, 001055, 001124, 00115...","[001011, 001045, 001075, 001117, 001130, 00115..."
1987-09-30,"[001065, 001078, 001112, 001169, 001181, 00118...","[001020, 001023, 001054, 001055, 001124, 00115...","[001011, 001045, 001075, 001117, 001130, 00115..."
1987-10-31,"[001065, 001078, 001112, 001169, 001181, 00118...","[001020, 001023, 001054, 001055, 001124, 00115...","[001011, 001045, 001075, 001117, 001130, 00115..."
...,...,...,...
2021-08-31,[],[],[]
2021-09-30,[],[],[]
2021-10-31,[],[],[]
2021-11-30,[],[],[]
2021-12-31,[],[],[]

In [117]:
HML_r = pd.DataFrame(index=HML_3_12m.index, columns=['High', 'Low'])
r_high = []
r_low = []
for date in HML_3_12m.index:
    r_high.append(mc_pct.loc[date, HML_3_12m.loc[date, 'High']].mean())
    r_low.append(mc_pct.loc[date, HML_3_12m.loc[date, 'Low']].mean())
HML_r['High']= r_high
HML_r['Low'] = r_low
HML_r['Diff'] = 1/2*(HML_r['High'] - HML_r['Low'])
HML_r

                High       Low      Diff
date
1987-06-30  0.064493  0.018977  0.022758
1987-07-31  0.030319  0.048753 -0.009217
1987-08-31  0.022008  0.015018  0.003495
1987-09-30 -0.005655  0.021228 -0.013442
1987-10-31 -0.307411 -0.240666 -0.033372
...              ...       ...       ...
2021-08-31       NaN       NaN       NaN
2021-09-30       NaN       NaN       NaN
2021-10-31       NaN       NaN       NaN
2021-11-30       NaN       NaN       NaN
2021-12-31       NaN       NaN       NaN

[415 rows x 3 columns]

In [122]:
Factors = pd.concat([SMB_r['Diff'], HML_r['Diff']], axis=1, join='inner')
Factors.columns = ['SMB', 'HML']
Factors = Factors*100

In [123]:
Factors.to_csv('3Factor.csv')

### 이상한 값 이유 찾기 ex> inf, 609, 13621 
#### 아마도 winsorize하면 되지 않을까 싶음...  from scipy.stats.mstats import winsorize 이용  --> 안 됨!
#### inf로 나오는 건 0으로 나눴기 때문이니까, 위에서 0.1로 바꿈

#### 위 아래 5%씩 날리자 --> 5%씩 날리니까 너무 변동성이 없다.
#### 위 아래 1%씩 날리자

In [382]:
mc_pct.loc['1994-03-31', SMB_2_12m.loc['1994-03-31', 'Big']].max()

977.75

In [391]:
mc_pct.max().isnull().sum()   #gvkey중 874개는 max값이 nan

872

In [385]:
mc_pct2 = mc_pct.loc[:,~mc_pct.max().isnull()]
mc_pct2

,001690,012141,160329,064768,184996,170617,117768,002176,010903,002968,...,293919,294007,296318,296753,296944,297209,311524,314866,317260,328032
date,,,,,,,,,,,,,,,,,,,,,
1986-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-01-31,0.370370,0.515544,NaN,NaN,NaN,NaN,NaN,0.099291,-0.164179,0.109467,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-02-28,0.261261,0.049573,NaN,NaN,NaN,NaN,NaN,0.083871,0.089286,-0.008000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-03-31,-0.059967,0.267957,NaN,NaN,NaN,NaN,NaN,0.047619,0.037419,-0.044084,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-04-30,0.228682,0.074936,NaN,NaN,NaN,NaN,NaN,-0.039773,-0.365079,-0.028571,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-31,0.040930,0.059563,0.074009,0.043034,0.070605,0.064777,0.148008,0.026259,0.009825,0.053828,...,-0.058577,-0.087688,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021-09-30,-0.075363,-0.067237,-0.080258,-0.051648,0.075466,-0.115855,-0.074559,-0.055204,-0.062326,0.012118,...,-0.093333,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021-10-31,0.058657,0.176291,0.107499,0.026602,0.436530,-0.046613,0.237134,0.052319,0.178456,0.037876,...,-0.019608,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021-11-30,0.103471,-0.003106,-0.041531,0.039924,0.027612,0.002751,0.278054,-0.037020,-0.035290,-0.065101,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021-12-31,0.074229,0.017333,0.020821,-0.049252,-0.076855,0.036646,-0.099920,0.081046,0.130386,-0.003022,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [386]:
mc_pct2.max().isnull().sum()

0

In [387]:
sorted(mc_pct2.loc['1994-03-31', SMB_2_12m.loc['1994-03-31', 'Big']], reverse=True)

[977.75,
 37.61885089839627,
 7.710723616718177,
 5.161953727506427,
 4.855702678920651,
 3.9229302352872137,
 3.352540373428792,
 3.3271837349397586,
 3.1536166549574496,
 2.3206482109213438,
 2.133187059427666,
 1.9310027598896045,
 1.4534884353028792,
 1.3666118395599192,
 1.30913253919949,
 1.2871134354906082,
 1.2168511465140086,
 1.2084655288744752,
 1.0795568982880157,
 1.0692840646651272,
 1.0322567741935478,
 1.0,
 0.9120333028201508,
 0.9033154813234692,
 0.8763473875126904,
 0.849695328368314,
 0.8233317048135094,
 0.7855667559605979,
 0.7787445520513978,
 0.7546325640511351,
 0.7500002865001092,
 0.7500000000000004,
 0.7499997500000002,
 0.6977109935868704,
 0.6933497954027044,
 0.6800000000000002,
 0.6743479814219364,
 0.6684495192886155,
 0.6240000398400065,
 0.6178283743574562,
 0.6176182634766372,
 0.5950907590759074,
 0.5891880402947527,
 0.5761583777047692,
 0.5747364898947271,
 0.5714285714285714,
 0.5642455782861344,
 0.5369460928438652,
 0.5357266336291344,
 0.5336172365766751,
 0.5158721390601182,
 0.5124906434401397,
 0.5123152709359604,
 0.4979614996907582,
 0.46659494351802033,
 0.44999999999999996,
 0.44654884244535054,
 0.4339622641509435,
 0.43020615267403617,
 0.4292039165602386,
 0.4285714285714286,
 0.3999999999999999,
 0.3943768996960493,
 0.38899804048049,
 0.3885359311026402,
 0.3884438399999999,
 0.375,
 0.37333678376571555,
 0.36363636363636354,
 0.36347420955215526,
 0.36023976599219965,
 0.3599103831384225,
 0.35512406375350536,
 0.34731840876147535,
 0.3463318112633178,
 0.34549619877928706,
 0.34541647582280977,
 0.3383268439479279,
 0.33689853870572617,
 0.3345197155558115,
 0.33451962044553807,
 0.3333333333333335,
 0.33333333333333326,
 0.33333333333333326,
 0.32994798946853754,
 0.32978751697606734,
 0.31888569861804195,
 0.3146664651851854,
 0.3123331066666666,
 0.3057782652683301,
 0.2914719967170689,
 0.29133271055110277,
 0.2881641273655293,
 0.2857610040226919,
 0.28571351836707515,
 0.27935944054659934,
 0.2772049309805604,
 0.2745294374726015,
 0.2727272727272727,
 0.26382522231627203,
 0.26044018385375045,
 0.25893146249325394,
 0.25751609300872635,
 0.25567466318893306,
 0.2520135916074886,
 0.25,
 0.25,
 0.25,
 0.25,
 0.24799992000000004,
 0.2479999199999996,
 0.24799967999999994,
 0.24799967999999994,
 0.24587750907815908,
 0.24569691705246277,
 0.24466601933602172,
 0.24045133784181139,
 0.23677835372532208,
 0.23543755079924122,
 0.23540504715200727,
 0.23529411764705888,
 0.2315272965857671,
 0.2309842375366571,
 0.2307142857142861,
 0.22685260874777935,
 0.22222222222222232,
 0.2217973231357553,
 0.21834451901565988,
 0.21626303938532354,
 0.2156560597888897,
 0.21438277056264532,
 0.2137135093550575,
 0.20833359236122595,
 0.2006403671428043,
 0.2006403671428041,
 0.20038464549395596,
 0.20000007626669536,
 0.19999999999999996,
 0.19999999999999996,
 0.19999999999999996,
 0.19999999999999996,
 0.1982281980397087,
 0.1974251995232419,
 0.1949962025316454,
 0.19362745098039214,
 0.19199958153846164,
 0.19073908991669564,
 0.18871512980036687,
 0.18769676884838438,
 0.18421052631578938,
 0.18387454905287814,
 0.18048289683325525,
 0.18032783032517763,
 0.17999999999999994,
 0.17853658536585382,
 0.17647058823529416,
 0.1739133144802265,
 0.1727377469435254,
 0.17241379310344818,
 0.17146133668362373,
 0.17096049814720482,
 0.17046936114732736,
 0.16666666666666674,
 0.16666666666666652,
 0.16551020043189735,
 0.16496829190060613,
 0.15999999999999992,
 0.1583831404385303,
 0.1578947368421053,
 0.15714219033463062,
 0.15576130366916274,
 0.1539407891479776,
 0.15120110667253694,
 0.1499999999999999,
 0.14958012564732526,
 0.14925373134328357,
 0.1490669797330697,
 0.14566644000000006,
 0.14416481208992282,
 0.14285714285714302,
 0.14285714285714302,
 0.1420319752449717,
 0.14110249616092307,
 0.13983978239999995,
 0.13796820012753663,
 0.13677467101459317,
 0.13599950545454553,
 0.1346666666666665,
 0.13446132923076948,
 0.13231094721115633,
 0.13082864924389814,
 0.1282051282051282,
 0.12737127371273704,
 0.1260492083594391,
 0.12578233522186322,
 0.12500000250000043,
 0.12500000000000022,
 0.12499999999999978,
 0.12499999999999956,
 0.1244626042165784,
 0.12413027980967839,
 0.12400000000000011,
 0.12399993983999003,
 0.12399983999999997,
 0.11764705896193761,
 0.11507650461538477,
 0.1124294824625951,
 0.10949996127999073,
 0.10891390325524797,
 0.10870878260480499,
 0.10812542325220509,
 0.10768921600643111,
 0.10693215819111335,
 0.10526315789473673,
 0.10486529955769996,
 0.10399977333333332,
 0.10344834963140848,
 0.1004612617228362,
 0.10000042760020311,
 0.10000000000000009,
 0.10000000000000009,
 0.09999999999999987,
 0.09999999999999964,
 0.09838126109433754,
 0.09683750936872548,
 0.0967742734651551,
 0.09523809523809534,
 0.09520182787509524,
 0.09459459459459452,
 0.09149402875944435,
 0.09117448570618647,
 0.09117397769073943,
 0.09106800754327793,
 0.09090909090909105,
 0.09090909090909083,
 0.09090909090909083,
 0.09090909090909083,
 0.0909090909090906,
 0.09090901338842317,
 0.08720924925635143,
 0.08571428571428585,
 0.08361057040225739,
 0.08333338407409152,
 0.08333333333333326,
 0.08333333333333326,
 0.07875473312164738,
 0.07692307692307687,
 0.07656953764132735,
 0.07547169811320709,
 0.07499999999999996,
 0.07409308462013975,
 0.07340483483948868,
 0.07322660547001036,
 0.07142857142857184,
 0.07142857142857162,
 0.0714285714285714,
 0.0714285714285714,
 0.06999999999999984,
 0.06998548019083173,
 0.06997050147492634,
 0.0687292535534938,
 0.06816269284712484,
 0.06723588190471452,
 0.06671022735056042,
 0.06666672803556506,
 0.06666666666666687,
 0.06666666666666665,
 0.06666666666666643,
 0.06666666666666621,
 0.06642952537497426,
 0.06301281673125891,
 0.05882352941176472,
 0.05882352941176472,
 0.05769230769230771,
 0.0560678100295966,
 0.0555555555555558,
 0.05555555555555558,
 0.054787149234693855,
 0.0540353680458463,
 0.0535714285714286,
 0.05314401622718057,
 0.05307558221684583,
 0.05268212147904672,
 0.050000000000000044,
 0.04959945599999993,
 0.04934921945656878,
 0.049180327868852514,
 0.04878048780487809,
 0.04796163069544357,
 0.04642758188505036,
 0.045454545454545414,
 0.045337111820473064,
 0.045090414545454705,
 0.04494112851681975,
 0.04444444444444451,
 0.04347826086956519,
 0.043253154999460586,
 0.041332879999999905,
 0.04059514149374821,
 0.04033335942809524,
 0.03966637571525555,
 0.03955226832258796,
 0.038744138145647256,
 0.03846153846153855,
 0.03846153846153855,
 0.038461538461538325,
 0.03815342769230767,
 0.037289494787489996,
 0.03728347659147446,
 0.0372576983772015,
 0.037037243987357416,
 0.036604448439962356,
 0.03632137149498771,
 0.03571428571428581,
 0.03571428571428581,
 0.03571428571428559,
 0.035545116698146195,
 0.034482758620689724,
 0.034482758620689724,
 0.034146341463414664,
 0.033673894912426894,
 0.03333333333333344,
 0.03333333333333344,
 0.0330682299422822,
 0.0330663040000001,
 0.03252488493387795,
 0.03252488493387773,
 0.032258064516129004,
 0.03133247614536128,
 0.031204274786538422,
 0.030999616208499337,
 0.030938833570412383,
 0.030600200233021235,
 0.030303030303030276,
 0.030223702998572133,
 0.02941176470588247,
 0.02941176470588247,
 0.028571428571428692,
 0.02631578947368407,
 0.026104976842105332,
 0.02499999999999991,
 0.02473065327809021,
 0.02260204081632633,
 0.022556390977443552,
 0.022513256536844217,
 0.021739056370498,
 0.021564980869565264,
 0.021276640054330498,
 0.02083333333333348,
 0.01976802429942115,
 0.018867999700972193,
 0.018867924528301883,
 0.017714091428571388,
 0.01652502360717656,
 0.01635578864876952,
 0.015873015873015817,
 0.014126859827721105,
 0.013106159895150737,
 0.011809394285714259,
 0.011627906976744207,
 0.011088370527901237,
 0.010960105217010296,
 0.00984898227183173,
 0.009540164090822367,
 0.008620558495829655,
 0.007702122715475879,
 0.007052186177715081,
 0.006738544474393482,
 0.004237568694961169,
 0.003673744523087441,
 0.002913130816064591,
 0.0015510746731663971,
 0.0013954786491767734,
 0.00048567265662935455,
 2.220446049250313e-16,
 2.220446049250313e-16,
 2.220446049250313e-16,
 2.220446049250313e-16,
 2.220446049250313e-16,
 2.220446049250313e-16,
 2.220446049250313e-16,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 ...]

In [388]:
mc_pct2.loc['1994-03-31', SMB_2_12m.loc['1994-03-31', 'Big']].max()

977.75

In [405]:
rank = mc_pct2.rank(1, 'first').apply(lambda x: pd.qcut(x, q=100, labels = range(1,101)) if not x.isnull().all() else x, axis=1)

In [406]:
mc_pct2[rank.isin([1,100])] = np.nan

C:\Users\jky93\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [407]:
mc_pct2

,001690,012141,160329,064768,184996,170617,117768,002176,010903,002968,...,293919,294007,296318,296753,296944,297209,311524,314866,317260,328032
date,,,,,,,,,,,,,,,,,,,,,
1986-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-01-31,0.370370,NaN,NaN,NaN,NaN,NaN,NaN,0.099291,NaN,0.109467,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-02-28,0.261261,0.049573,NaN,NaN,NaN,NaN,NaN,0.083871,0.089286,-0.008000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-03-31,-0.059967,0.267957,NaN,NaN,NaN,NaN,NaN,0.047619,0.037419,-0.044084,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987-04-30,NaN,0.074936,NaN,NaN,NaN,NaN,NaN,-0.039773,NaN,-0.028571,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-31,0.040930,0.059563,NaN,0.043034,NaN,0.064777,NaN,0.026259,0.009825,0.053828,...,-0.058577,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021-09-30,-0.075363,-0.067237,-0.080258,-0.051648,NaN,NaN,-0.074559,-0.055204,-0.062326,0.012118,...,-0.093333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021-10-31,0.058657,NaN,NaN,0.026602,NaN,NaN,NaN,0.052319,NaN,0.037876,...,-0.019608,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021-11-30,NaN,-0.003106,-0.041531,NaN,NaN,0.002751,NaN,-0.037020,-0.035290,-0.065101,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021-12-31,0.074229,0.017333,0.020821,-0.049252,NaN,0.036646,NaN,NaN,NaN,-0.003022,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## 다시 팩터 찾기

In [408]:
SMB_r = pd.DataFrame(index=SMB_2_12m.index, columns=SMB_2.columns)
r_big = []
r_small = []
for date in SMB_2_12m.index:
    r_big.append(mc_pct2.loc[date, SMB_2_12m.loc[date, 'Big']].mean())
    r_small.append(mc_pct2.loc[date, SMB_2_12m.loc[date, 'Small']].mean())
SMB_r['Big']= r_big
SMB_r['Small'] = r_small
SMB_r

                 Big     Small
date
1987-06-30  0.008464  0.028840
1987-07-31  0.020670  0.029882
1987-08-31 -0.001407  0.016913
1987-09-30 -0.011565 -0.013551
1987-10-31 -0.266587 -0.274336
...              ...       ...
2021-08-31 -0.000164  0.000576
2021-09-30 -0.000556 -0.007042
2021-10-31  0.000131  0.004426
2021-11-30 -0.000396 -0.008915
2021-12-31  0.000104  0.003114

[415 rows x 2 columns]

In [409]:
SMB_r['Diff'] = 1/3*(SMB_r['Big'] - SMB_r['Small'])

In [410]:
HML_3_12m = pd.DataFrame(np.repeat(HML_3.values, 12, axis=0), columns=HML_3.columns)[:-5]
HML_3_12m.index = mktcap.loc['1987-06-30':,:].index
HML_3_12m

,High,Medium,Low
date,,,
1987-06-30,"[001065, 001078, 001112, 001169, 001181, 00118...","[001020, 001023, 001054, 001055, 001124, 00115...","[001011, 001045, 001075, 001117, 001130, 00115..."
1987-07-31,"[001065, 001078, 001112, 001169, 001181, 00118...","[001020, 001023, 001054, 001055, 001124, 00115...","[001011, 001045, 001075, 001117, 001130, 00115..."
1987-08-31,"[001065, 001078, 001112, 001169, 001181, 00118...","[001020, 001023, 001054, 001055, 001124, 00115...","[001011, 001045, 001075, 001117, 001130, 00115..."
1987-09-30,"[001065, 001078, 001112, 001169, 001181, 00118...","[001020, 001023, 001054, 001055, 001124, 00115...","[001011, 001045, 001075, 001117, 001130, 00115..."
1987-10-31,"[001065, 001078, 001112, 001169, 001181, 00118...","[001020, 001023, 001054, 001055, 001124, 00115...","[001011, 001045, 001075, 001117, 001130, 00115..."
...,...,...,...
2021-08-31,[],[],[]
2021-09-30,[],[],[]
2021-10-31,[],[],[]
2021-11-30,[],[],[]
2021-12-31,[],[],[]

In [411]:
HML_r = pd.DataFrame(index=HML_3_12m.index, columns=['High', 'Low'])
r_high = []
r_low = []
for date in HML_3_12m.index:
    r_high.append(mc_pct2.loc[date, HML_3_12m.loc[date, 'High']].mean())
    r_low.append(mc_pct2.loc[date, HML_3_12m.loc[date, 'Low']].mean())
HML_r['High']= r_high
HML_r['Low'] = r_low
HML_r['Diff'] = 1/2*(HML_r['High'] - HML_r['Low'])
HML_r

                High       Low      Diff
date
1987-06-30  0.029924  0.022326  0.003799
1987-07-31  0.030348  0.024528  0.002910
1987-08-31  0.013858  0.013325  0.000267
1987-09-30 -0.012351 -0.017561  0.002605
1987-10-31 -0.297853 -0.249406 -0.024224
...              ...       ...       ...
2021-08-31       NaN       NaN       NaN
2021-09-30       NaN       NaN       NaN
2021-10-31       NaN       NaN       NaN
2021-11-30       NaN       NaN       NaN
2021-12-31       NaN       NaN       NaN

[415 rows x 3 columns]

In [412]:
Factors = pd.concat([SMB_r['Diff'], HML_r['Diff']], axis=1, join='inner')
Factors.columns = ['SMB', 'HML']
Factors = Factors*100

In [413]:
Factors.to_csv('winsorized 100Q 3Factor.csv')